-- Step 5 (embeddings): one row per item per embedding space, generated by the
-- embed-items command via Voyage AI. Kept separate from paid_ads/ugc_items so
-- items can be re-embedded with a different model without schema churn.
create extension if not exists vector;

create table if not exists item_embeddings (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references pipeline_runs(id) on delete cascade,
  item_type text not null check (item_type in ('paid_ad', 'ugc_item')),
  item_id uuid not null,
  space text not null check (space in ('icp', 'format', 'hook')),
  embedding_model text not null,
  source_text text not null,
  embedding vector(1024) not null,
  created_at timestamptz not null default now(),
  unique (item_type, item_id, space, embedding_model)
);

create index if not exists item_embeddings_run_idx on item_embeddings(run_id);
create index if not exists item_embeddings_space_idx on item_embeddings(item_type, space);
