window.STRATEGY_DATA = {
  "campaign": "QV Summer Product Launch",
  "product": "QV (Ego Pharmaceuticals)",
  "run_id": "789d6619-cd52-49e7-ab2f-9576d1055738",
  "sources": [
    {
      "key": "ugc",
      "label": "UGC",
      "persona_count": 5,
      "generation_count": 39,
      "icps": [
        {
          "name": "Adult women seeking to optimize their daily wellness and skincare routines through effective, time-saving solutions.",
          "persona": "Adult women seeking to optimize their daily wellness and skincare routines through effective, time-saving solutions.",
          "pains": [
            "dull or aging skin",
            "lack of consistent energy",
            "overwhelming beauty routines",
            "visible signs of stress"
          ],
          "scrolls_for": [
            "skincare tutorials",
            "evidence-based wellness tips",
            "morning routine inspiration",
            "honest product reviews",
            "self-care hacks"
          ],
          "quote": "I just want a simple routine that actually delivers visible results.",
          "tags": [
            "glowup",
            "skincare",
            "grwm",
            "wonenizm",
            "косметика",
            "neckcare",
            "skincareroutine",
            "beauty",
            "antiaging",
            "selfcare"
          ],
          "count": 7,
          "videos": [
            {
              "handle": "@royalbeutysalon",
              "nickname": "🥰💯🥳",
              "country": "India",
              "metric": "1.1M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620694203479198992.jpg",
              "description": "#trendingnow #foryou #tiktok #sapny ",
              "hook": "Satisfying close-up of a facial massage with a light cleanser, showing glowing skin and gentle hand movements.",
              "format": "tutorial",
              "tier": "MEGA",
              "score": 550.28,
              "video_url": "https://www.tiktok.com/@royalbeutysalon/video/7620694203479198992",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620694203479198992",
              "picked": true
            },
            {
              "handle": "@blonbievvanili",
              "nickname": "Блонди в ванили🤍",
              "country": "Russia",
              "metric": "514K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641583710785047841.jpg",
              "description": "#glowup #skincare #grwm #wonenizm #косметика ",
              "hook": "A perfectly organized pink skincare shelf with a Russian text overlay that humorously states, \"When I bought this shelf, but I have little skincare, and it looks very rough, to be honest.\"",
              "format": "grwm",
              "tier": "MEGA",
              "score": 353.54,
              "video_url": "https://www.tiktok.com/@blonbievvanili/video/7641583710785047841",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641583710785047841",
              "picked": false
            },
            {
              "handle": "@kartikvibes03",
              "nickname": "Kartikvibes03",
              "country": "India",
              "metric": "959K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DY1ZLysRaPk.jpg",
              "description": "Skin care routine ❤️ as always \n\n.\n\n.\n\n.\n\n.\n\n.\n\n#kartikvibes03 #royalenfield #hunter350 #instagram #explore",
              "hook": "Watch this creator meticulously wash their Royal Enfield motorcycle, calling it their 'men skin care routine'. It's a detailed look at bike maintenance.",
              "format": "tutorial",
              "tier": "HIGH",
              "score": 88.52,
              "video_url": "https://www.instagram.com/p/DY1ZLysRaPk/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DY1ZLysRaPk/embed",
              "picked": false
            },
            {
              "handle": "@mia.carter587",
              "nickname": "Mia Carter",
              "country": "United States",
              "metric": "43K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641922206930423071.jpg",
              "description": "Don't forget this part of your skincare routine #neckcare #skincareroutine #beauty #antiaging #selfcare ",
              "hook": "POV: This expert is pointing out the obvious wrinkles on a woman's neck, reminding you to care for this often-forgotten area in your skincare routine.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 37.34,
              "video_url": "https://www.tiktok.com/@mia.carter587/video/7641922206930423071",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641922206930423071",
              "picked": false
            },
            {
              "handle": "@bonita.glow3",
              "nickname": "bonita.glow",
              "country": "United States",
              "metric": "151K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643021152381586702.jpg",
              "description": "ing to consistency is KEY look at that difference.Try HKH Plant Retinol Time capsule.🔥🫦🍟 ⚡️🧚🏻‍♀️🗽🦩#cuidadodelapiel#glowup#antiedad#antiarrugas#hkh ",
              "hook": "Watch the dramatic transformation as skincare creates a visible difference, proving consistency is key for anti-aging results.",
              "format": "before after",
              "tier": "MODERATE",
              "score": 30.25,
              "video_url": "https://www.tiktok.com/@bonita.glow3/video/7643021152381586702",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643021152381586702",
              "picked": false
            },
            {
              "handle": "@cutiepatooties609",
              "nickname": "cutiepatooties",
              "country": "South Korea",
              "metric": "240K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642608255612603661.jpg",
              "description": "LISTEN TO THIS 🤯 #skincare #collagen #medicube #collagenjelly #faceroutine ",
              "hook": "This 61-year-old woman reveals her secret to reversing aging with a collagen jelly, leaving younger women asking for her routine.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 26.67,
              "video_url": "https://www.tiktok.com/@cutiepatooties609/video/7642608255612603661",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642608255612603661",
              "picked": false
            },
            {
              "handle": "@dailybelanf",
              "nickname": "Bela ✨",
              "country": "Brazil",
              "metric": "45K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641385157231938837.jpg",
              "description": "Arrumando meu quarto asmr✨ #organizacao #limpeza #girls #quarto #autocuidado ",
              "hook": "A satisfying ASMR video shows a room being meticulously organized, featuring skincare products and personal care items.",
              "format": "voiceover",
              "tier": "MODERATE",
              "score": 25.8,
              "video_url": "https://www.tiktok.com/@dailybelanf/video/7641385157231938837",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641385157231938837",
              "picked": false
            }
          ]
        },
        {
          "name": "A tech-savvy millennial professional balancing a fast-paced career with a growing desire for holistic wellness and sustainable living.",
          "persona": "A tech-savvy millennial professional balancing a fast-paced career with a growing desire for holistic wellness and sustainable living.",
          "pains": [
            "burnout from hustle culture",
            "skin issues caused by stress",
            "lack of work-life balance",
            "difficulty finding authentic brands"
          ],
          "scrolls_for": [
            "aesthetic morning routines",
            "honest product reviews",
            "mental health tips",
            "quick healthy meal prep",
            "sustainable fashion hauls"
          ],
          "quote": "I just want a routine that actually works for my busy lifestyle.",
          "tags": [
            "dadsbirthday",
            "suprise",
            "thegentlemen",
            "gift",
            "birthdaypresent",
            "softvibes",
            "gentlebeauty",
            "dailysweetness",
            "naturalcharm"
          ],
          "count": 5,
          "videos": [
            {
              "handle": "@therichardssiblings",
              "nickname": "TheRichards",
              "country": "United States",
              "metric": "1M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7626478759897517334.jpg",
              "description": "Anyone else’s dad love ‘The Gentlemen’? #dadsbirthday #suprise #thegentlemen #gift #birthdaypresent ",
              "hook": "Recreating scenes from 'The Gentlemen' for Dad's 60th birthday is a hilarious and heartfelt way to celebrate his favorite film.",
              "format": "skit",
              "tier": "HIGH",
              "score": 95.24,
              "video_url": "https://www.tiktok.com/@therichardssiblings/video/7626478759897517334",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7626478759897517334",
              "picked": true
            },
            {
              "handle": "@sgckxig84wymull",
              "nickname": "Calliope",
              "country": "United States",
              "metric": "86K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7628985209467292942.jpg",
              "description": "Soft lights and gentle smiles—life’s sweetest moments  #SoftVibes #GentleBeauty #DailySweetness #NaturalCharm",
              "hook": "A woman with dark, wavy hair and a soft smile shares a serene moment, bathed in gentle lighting.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 77.93,
              "video_url": "https://www.tiktok.com/@sgckxig84wymull/video/7628985209467292942",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7628985209467292942",
              "picked": false
            },
            {
              "handle": "@cityzen.moe",
              "nickname": "Mo Wael",
              "country": "United Kingdom",
              "metric": "410K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DXCuTs2t7RT.jpg",
              "description": "Just a quick reminder 👍\n\n#mancity #chelsea #arsenal #titlerace premierleague",
              "hook": "Wearing a Manchester City jersey, a man takes a drink from an Arsenal-branded water bottle, reminding viewers to stay hydrated.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 57.66,
              "video_url": "https://www.instagram.com/p/DXCuTs2t7RT/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DXCuTs2t7RT/embed",
              "picked": false
            },
            {
              "handle": "@mxryccx",
              "nickname": "mxryccx",
              "country": "Thailand",
              "metric": "43K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7640223162185026824.jpg",
              "description": "Nong Rann >>>>>  #LoveBeyondDreamsSeries #LoveBeyondDreams #ayaorapan #glseries #wlw  @ayaorapan ",
              "hook": "A young woman with long dark hair and a white blazer smiles gently, adorned with hoop earrings and a heart pendant necklace.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 42.31,
              "video_url": "https://www.tiktok.com/@mxryccx/video/7640223162185026824",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7640223162185026824",
              "picked": false
            },
            {
              "handle": "@marygarzadbmoqz",
              "nickname": "ActiveMabel",
              "country": "United States",
              "metric": "49K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7630038322580180255.jpg",
              "description": "Sitting all day? 🪑 Your hips and back start to feel stiff and stuck. Before bed, try these 5 gentle swings — 20 times each. They’ll help release tension, open your hips, and ease your back. ✨part 2 #BackPainRelief #HipMobility #BedtimeRoutine #ReleaseTension #HealthyHips",
              "hook": "Struggling with back and hip pain? Learn 5 gentle bedtime swings to release tension and improve mobility.",
              "format": "tutorial",
              "tier": "MODERATE",
              "score": 42.29,
              "video_url": "https://www.tiktok.com/@marygarzadbmoqz/video/7630038322580180255",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7630038322580180255",
              "picked": false
            }
          ]
        },
        {
          "name": "Young adults in their late teens to early twenties navigating lifestyle transitions and early independence.",
          "persona": "Young adults in their late teens to early twenties navigating lifestyle transitions and early independence.",
          "pains": [
            "limited disposable income",
            "academic and social burnout",
            "uncertainty about the future",
            "pressure to maintain a social media image"
          ],
          "scrolls_for": [
            "relatable student life struggles",
            "affordable fashion hauls",
            "quick dorm-friendly recipes",
            "honest mental health chats",
            "entry-level career advice"
          ],
          "quote": "I'm just trying to balance my social life without going broke.",
          "tags": [
            "skincare",
            "glowup",
            "бьютиблог",
            "grwm",
            "косметика",
            "set1awanade",
            "facewash",
            "barberdaily",
            "fyp",
            "xyzabc"
          ],
          "count": 12,
          "videos": [
            {
              "handle": "@japan_cosmehub",
              "nickname": "japan_cosmehub",
              "country": "Japan",
              "metric": "481K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620765169139944735.jpg",
              "description": "Perfect whip difference👀‼️ #jbeauty #japanshopping #japanhaul #beautytok #japantravel ",
              "hook": "Struggling to choose between Japan's popular 'Perfect Whip' cleansers? This video breaks down the differences between the blue, pink, white, and green formulas to help you pick the best one for your skin type!",
              "format": "voiceover",
              "tier": "MEGA",
              "score": 480.72,
              "video_url": "https://www.tiktok.com/@japan_cosmehub/video/7620765169139944735",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620765169139944735",
              "picked": true
            },
            {
              "handle": "@sosmedsulsel",
              "nickname": "SOSMED SULSEL",
              "country": "Indonesia",
              "metric": "1.4M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643316137253424391.jpg",
              "description": "Balai Besar Pengawas Obat dan Makanan (BBPOM) Makassar menyita 7.092 picis skincare dari berbagai merek produk kosmetik ilegal dan mengandung merkuri di Kota Makassar, Sulawesi Selatan (Sulsel). Produk skincare atau kosmetik perawatan kulit ini dibuat di salah satu rumah yang diproduksi wanita berinisial S (28). \"Ditemukan aktivitas produksi kosmetik berupa sarana tidak memiliki izin produksi/sarana ilegal dan produk kosmetik ilegal mengandung bahan berbahaya, dengan rincian produk jadi sebanyak 8 item, 7.092 picis,\" ujar Kepala BBPOM Makassar Yosef Dwi Irwan Prakasa Setiawan saat konferensi pers di kantornya Jalan Baji Minasa, Kamis (21/5/2026). Produk kosmetik ilegal mengandung bahan b3rbah4y4, dengan rincian produk jadi sebanyak 8 item. Total yang disita 7.092 picis serta ditemukan bahan baku produk, produk rumahan, kemasan, label dan alat produksi sederhana. \"Produk yang disita terdiri dari Putri Glow Face Toner, Putri Glow Facial Wash, Putri Glow Day Cream, Putri Glow Night Cream, Putri Glow Serum C hingga Putri Glow Body Lotion,\" jelas Yosef. Yosef mengatakan, ribuan picis dari 6 produk tersebut diproduksi menggunakan bahan b3rbah4y4. Hasil pengujian laboratorium menunjukkan produk positif mengandung merkuri, hidrokuinon dan asam retinoat. \"Terhadap produk kosmetik ilegal ini telah pengujian di laboratorium BBPOM di Makassar dan hasilnya positif merkuri, hidrokinon dan asam retinoat,\" jelasnya. Di lokasi tersebut, petugas turut menemukan bahan baku kosmetik tanpa izin edar BPOM seperti DL Hydroquinone Tretinoin Babyface 3, La Bella Cream, Erna Whitening Cream, Super SP Special dan BL Cream. Selain itu ditemukan alat produksi sederhana berupa ember, mixer, corong, saringan hingga hot air gun. \"Jadi pelaku mencampur produk legal dan ilegal di kosmetik produksinya,\" ungkap Yosef. BBPOM Makassar mengungkap nilai ekonomi seluruh barang temuan diperkirakan mencapai Rp 700 juta. Produk tersebut dipasarkan secara online dan offline dalam bentuk paket skincare. \"Rata-rata produksi per pekan bisa mencapai 300 sampai dengan 500 paket, dengan harga jual per paketnya Rp 130 ribu maka estimasi omzet per pekan bisa mencapai Rp 39 juta sampai Rp 65 juta,\" ungkap Yosef. Diketahui, sejumlah produk kosmetik ilegal dan mengandung bahan b3rbah4y4 itu disita dari di sebuah rumah di Kelurahan Paropo, Kecamatan Panakkukang, Makassar, Selasa (19/5). Rumah tersebut dijadikan sebagai pabrik skincare. Adapun merek produk skincare ilegal dan b3rbah4y4 yang disita sebagai berikut: Putri Glow Face Toner Putri Glow Facial Wash Putri Glow Day Cream Putri Glow Night Cream Putri Glow Serum C Putri Glow Body Lotion Selengkapnya di : https://www.detik.com/sulsel/makassar/d-8498828/7-092-skincare-ilegal-disita-di-pabrik-rumahan-makassar-ini-daftar-mereknya",
              "hook": "Illegal skincare worth millions seized in Makassar! Authorities raid a home factory producing dangerous, mercury-laced cosmetics, including popular brands.",
              "format": "voiceover",
              "tier": "MEGA",
              "score": 410.68,
              "video_url": "https://www.tiktok.com/@sosmedsulsel/video/7643316137253424391",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643316137253424391",
              "picked": false
            },
            {
              "handle": "@ayamnicher",
              "nickname": "ayamnicher",
              "country": "France",
              "metric": "597K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620549421247237397.jpg",
              "description": "Fresh and clean with @Garnier  #garnierskin #serumcleanser #fastbright #vitaminec #ad",
              "hook": "Glow up your skin! See how this Garnier Vitamin C serum cleanser delivers a fresh and bright complexion.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 195.74,
              "video_url": "https://www.tiktok.com/@ayamnicher/video/7620549421247237397",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620549421247237397",
              "picked": false
            },
            {
              "handle": "@linh1001022",
              "nickname": "Mỹ Linhhhh",
              "country": "Vietnam",
              "metric": "257K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7626374637940772114.jpg",
              "description": "#srm #suaruamat #colorkey #skincare #xuhuong ",
              "hook": "A hand holds up a green Luminous Purifying Gel Cleanser with a matching green sponge, asking viewers if they're getting enough product.",
              "format": "product review",
              "tier": "HIGH",
              "score": 188.89,
              "video_url": "https://www.tiktok.com/@linh1001022/video/7626374637940772114",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7626374637940772114",
              "picked": false
            },
            {
              "handle": "@mina_biyou0",
              "nickname": "みなきメンズ美容",
              "country": "Japan",
              "metric": "699K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7631825940439633173.jpg",
              "description": "シカリ洗顔を2週間使ったレビュー載せます！ #シカリ #SHIKARI #洗顔 #正直レビュー #tiktokショップ ",
              "hook": "Is this the \"magic\" facial cleanser that delivers on its promises? See the unfiltered results after two weeks of use!",
              "format": "product review",
              "tier": "HIGH",
              "score": 137.16,
              "video_url": "https://www.tiktok.com/@mina_biyou0/video/7631825940439633173",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7631825940439633173",
              "picked": false
            },
            {
              "handle": "@dayanara.wellness",
              "nickname": "Daya",
              "country": "United States",
              "metric": "230K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641358220883217694.jpg",
              "description": "Not just face wash but so many different serums and masks and treatments #pep #tides #ghkcu #klow #wellness ",
              "hook": "Frustrated with your skincare routine? Watch as this creator tries every product imaginable, hoping for a breakthrough that never seems to come.",
              "format": "tutorial",
              "tier": "HIGH",
              "score": 129.52,
              "video_url": "https://www.tiktok.com/@dayanara.wellness/video/7641358220883217694",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641358220883217694",
              "picked": false
            },
            {
              "handle": "@blonbievvanili",
              "nickname": "Блонди в ванили🤍",
              "country": "Russia",
              "metric": "150K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642294197332004128.jpg",
              "description": "#skincare #glowup #бьютиблог #grwm #косметика ",
              "hook": "A dreamy pink-themed skincare collection is neatly organized in a rotating carousel organizer, showcasing popular beauty products for a glow-up.",
              "format": "product review",
              "tier": "HIGH",
              "score": 103.23,
              "video_url": "https://www.tiktok.com/@blonbievvanili/video/7642294197332004128",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642294197332004128",
              "picked": false
            },
            {
              "handle": "@flaviasantanav",
              "nickname": "Flávia Santana | UGC Creator",
              "country": "Brazil",
              "metric": "908K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DWTu0EEkR1d.jpg",
              "description": "Me explica como um produto consegue limpar, tratar e ainda deixar esse glow na pele? ✨\n\nO novo Serumnete chegou pra provar que dá sim pra ter uma pele radiante sem complicar a rotina. 💛\nCuida como um sérum e limpa como sabonete, tudo em um único passo!\n\nPerfeito pra quem não tem tempo ou até preguiça mesmo, mas não abre mão de uma pele bonita, uniforme e com aquele glow natural.\n\n@GarnierBrasil\n#LimpezaGarnier #SerumneteGarnier #publi",
              "hook": "This Garnier \"Serumnete\" promises to clean, treat, and add glow to your skin in one easy step, simplifying your routine for radiant results.",
              "format": "product review",
              "tier": "HIGH",
              "score": 78.29,
              "video_url": "https://www.instagram.com/p/DWTu0EEkR1d/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DWTu0EEkR1d/embed",
              "picked": false
            },
            {
              "handle": "@accryzn",
              "nickname": "Ryzn",
              "country": "Indonesia",
              "metric": "136K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643279342906117394.jpg",
              "description": "ohhh ternyata yang basic doang udah cukup banget buat cowok wkwk #set1awanade #skincare #facewash #barberdaily ",
              "hook": "Gamers, get ready for the ultimate skincare routine! Learn the basic steps to keep your face fresh without the fuss.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 61.83,
              "video_url": "https://www.tiktok.com/@accryzn/video/7643279342906117394",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643279342906117394",
              "picked": false
            },
            {
              "handle": "@spellrlabs",
              "nickname": "Alex",
              "country": "United States",
              "metric": "89K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641735149717081374.jpg",
              "description": "😝Summer ascension protocol in full effect Link in bio #mt2 #peptide ",
              "hook": "Cetaphil cleanser, Accutane, and vials of MT2 peptides are laid out, suggesting a serious skincare or body transformation routine.",
              "format": "product review",
              "tier": "HIGH",
              "score": 61.26,
              "video_url": "https://www.tiktok.com/@spellrlabs/video/7641735149717081374",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641735149717081374",
              "picked": false
            },
            {
              "handle": "@nandid_",
              "nickname": "nandid_",
              "country": "United States",
              "metric": "113K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7624273645296307476.jpg",
              "description": "If you’re dealing with whiteheads that keep coming back, slow this part down   #sacleanser #whiteheads #acneskincare #skincareproducts#cerave",
              "hook": "Struggling with persistent whiteheads? This video slows down to reveal the key to tackling them with CeraVe cleanser.",
              "format": "product review",
              "tier": "MODERATE",
              "score": 41.88,
              "video_url": "https://www.tiktok.com/@nandid_/video/7624273645296307476",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7624273645296307476",
              "picked": false
            },
            {
              "handle": "@bio_o6",
              "nickname": "Systemfile_",
              "country": "Thailand",
              "metric": "75K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7637241133013159190.jpg",
              "description": "MOTHER FATHER GENTLEMAN ｜ib：tesxanna｜ cr-X ：chuuyou｜BBaifern_O｜abysskenn｜lemonskyhopp｜Nine91x  #อู่อู๋เซฟ #auausve #edit #fyp ",
              "hook": "Two men in sharp white suits pose intensely, one holding a small object near his face, with the word \"GENTLEMAN\" glowing between them. Moody lighting and a close-up perspective create a dramatic and stylish aesthetic.",
              "format": "other",
              "tier": "MODERATE",
              "score": 40.43,
              "video_url": "https://www.tiktok.com/@bio_o6/video/7637241133013159190",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7637241133013159190",
              "picked": false
            }
          ]
        },
        {
          "name": "A diverse broad-market consumer across all age groups looking for reliable, everyday skincare and wellness solutions.",
          "persona": "A diverse broad-market consumer across all age groups looking for reliable, everyday skincare and wellness solutions.",
          "pains": [
            "cluttered markets with too many niche products",
            "lack of universal skin solutions",
            "expensive treatments that don't last",
            "confusing ingredient lists"
          ],
          "scrolls_for": [
            "relatable daily routines",
            "before and after transformations",
            "honest product reviews",
            "simple self-care tips",
            "dermatologist recommendations"
          ],
          "quote": "I just want a simple routine that actually works for my skin.",
          "tags": [
            "bubu",
            "dudu",
            "bubududu",
            "love",
            "cute",
            "pakistan",
            "rajabfamily",
            "pakistani_tik_tok",
            "haniaamir",
            "viral"
          ],
          "count": 10,
          "videos": [
            {
              "handle": "@user6188811970192",
              "nickname": "JB Tech Scout",
              "country": "Malaysia",
              "metric": "1.2M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7631423938140048661.jpg",
              "description": "Rasa macam masuk dalam scene tu 😳✨ #HONOR600Pro #FYP #2026",
              "hook": "A martial arts-inspired showdown unfolds in a bustling city street with a basketball player and a dapper gentleman observing.",
              "format": "other",
              "tier": "MEGA",
              "score": 596.72,
              "video_url": "https://www.tiktok.com/@user6188811970192/video/7631423938140048661",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7631423938140048661",
              "picked": true
            },
            {
              "handle": "@jellymakeupthings0",
              "nickname": "jellymakeupthings0",
              "country": "United States",
              "metric": "523K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642315251261672726.jpg",
              "description": "ASMR Skincare Routine on Watermelon relaxing #shorts #makeup #jellymakeupthing0 #relaxingvideos #foryoupage❤️❤️ ",
              "hook": "Experience a unique ASMR skincare routine as a hand with googly eyes applies product to a watermelon, creating a strangely satisfying sensory experience.",
              "format": "asmr",
              "tier": "MEGA",
              "score": 367.49,
              "video_url": "https://www.tiktok.com/@jellymakeupthings0/video/7642315251261672726",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642315251261672726",
              "picked": false
            },
            {
              "handle": "@jellymakeupthings0",
              "nickname": "jellymakeupthings0",
              "country": "United States",
              "metric": "218K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641212102467767574.jpg",
              "description": "Skincare on Watermelon ASMR #shorts #makeup #jellymakeupthing0 #relaxingvideos #foryoupage❤️❤️ ",
              "hook": "Glittery green goo covers a watermelon's face in this oddly satisfying ASMR skincare routine.",
              "format": "asmr",
              "tier": "HIGH",
              "score": 153.37,
              "video_url": "https://www.tiktok.com/@jellymakeupthings0/video/7641212102467767574",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641212102467767574",
              "picked": false
            },
            {
              "handle": "@jed.charita",
              "nickname": "JED CHARITA",
              "country": "United States",
              "metric": "1.1M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7634726616182066462.jpg",
              "description": "Whether or not the birds can be successfully hatched.#animals #Foryou #love#cute#tiktok ",
              "hook": "A person gently strokes a white cockatoo with a feather, capturing a moment of pure avian bliss.",
              "format": "voiceover",
              "tier": "HIGH",
              "score": 70.51,
              "video_url": "https://www.tiktok.com/@jed.charita/video/7634726616182066462",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7634726616182066462",
              "picked": false
            },
            {
              "handle": "@hania.amir.2",
              "nickname": "Hania amir",
              "country": "Pakistan",
              "metric": "306K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7644178648379002134.jpg",
              "description": "#haniaamir #viral #vlogs #FYP #foryoupage❤️❤️ ",
              "hook": "A woman in pajamas and a towel-wrapped head holds a pink beauty tool, ready for her nighttime skincare routine in a yellow-accented kitchen.",
              "format": "vlog",
              "tier": "MODERATE",
              "score": 49.34,
              "video_url": "https://www.tiktok.com/@hania.amir.2/video/7644178648379002134",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7644178648379002134",
              "picked": false
            },
            {
              "handle": "@zoraiz20262",
              "nickname": "Sher da puttar",
              "country": "Pakistan",
              "metric": "58K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642101401115577622.jpg",
              "description": "#pakistan #rajabfamily #pakistani_tik_tok ",
              "hook": "A woman shares a skincare tip after her routine, suggesting a filter can make skin look flawless, with a funny emoji.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 42.46,
              "video_url": "https://www.tiktok.com/@zoraiz20262/video/7642101401115577622",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642101401115577622",
              "picked": false
            },
            {
              "handle": "@kobetherottie_",
              "nickname": "Kobe The Rottie",
              "country": "Australia",
              "metric": "398K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643380730596314388.jpg",
              "description": "still looking for the guard dog we bought 🤔 #rottweiler #dogsoftiktok #funny #viral #doglover ",
              "hook": "This Rottweiler is so gentle and cuddly, it's hard to believe it's supposed to be a guard dog!",
              "format": "pov",
              "tier": "MODERATE",
              "score": 40.26,
              "video_url": "https://www.tiktok.com/@kobetherottie_/video/7643380730596314388",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643380730596314388",
              "picked": false
            },
            {
              "handle": "@budu_2010",
              "nickname": "The story of BuDu",
              "country": "Vietnam",
              "metric": "540K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7631282307709586696.jpg",
              "description": "Bé buồn 🥺 #bubu #dudu #bubududu #love #cute ",
              "hook": "A cute plush panda toy is gently poked by a finger, creating an adorable and heartwarming moment perfect for a relaxing scroll.",
              "format": "other",
              "tier": "MODERATE",
              "score": 39.39,
              "video_url": "https://www.tiktok.com/@budu_2010/video/7631282307709586696",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7631282307709586696",
              "picked": false
            },
            {
              "handle": "@bonita.glow3",
              "nickname": "bonita.glow",
              "country": "United States",
              "metric": "154K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643771656292289806.jpg",
              "description": "ing to consistency is KEY look at that difference.Try HKH Plant Retinol Time capsule.🔥🫦🍟 ⚡️🧚🏻‍♀️🗽🦩#cuidadodelapiel#glowup#antiedad#antiarrugas#hkh ",
              "hook": "A man with dramatic eye makeup showcases the dramatic difference in skin texture after using a new product, highlighting anti-aging benefits.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 30.69,
              "video_url": "https://www.tiktok.com/@bonita.glow3/video/7643771656292289806",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643771656292289806",
              "picked": false
            },
            {
              "handle": "@sanwariya_cosmetics_hapur",
              "nickname": "SANWARIYA COSMETIC & JEWELLERY STORE || HAPUR",
              "country": "India",
              "metric": "27K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYGz3Zcsk8B.jpg",
              "description": "Variety of cleansers",
              "hook": "A shopkeeper showcases a vibrant display of cleansers and skincare products, highlighting a diverse range of brands and packaging.",
              "format": "other",
              "tier": "MODERATE",
              "score": 22.01,
              "video_url": "https://www.instagram.com/p/DYGz3Zcsk8B/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYGz3Zcsk8B/embed",
              "picked": false
            }
          ]
        },
        {
          "name": "A diverse demographic of individuals across all age groups looking for universal skin and health solutions that fit any lifestyle.",
          "persona": "A diverse demographic of individuals across all age groups looking for universal skin and health solutions that fit any lifestyle.",
          "pains": [
            "Confusion over age-specific marketing",
            "Finding products safe for the whole family",
            "Generic solutions that lack efficacy",
            "Inconsistent daily routines"
          ],
          "scrolls_for": [
            "Multi-generational success stories",
            "Simple skin health tips",
            "Universal wellness hacks",
            "Dermatologist-approved basics",
            "Family-friendly lifestyle content"
          ],
          "quote": "I just want something effective that works for everyone in my house.",
          "tags": [
            "funnyvideo",
            "funnystatus",
            "foryou",
            "foryoupage",
            "viral",
            "fyp",
            "rosalina",
            "peach",
            "supermario",
            "supermariogalaxy"
          ],
          "count": 5,
          "videos": [
            {
              "handle": "@merakevrenicom",
              "nickname": "Merak Evreni",
              "country": "Turkey",
              "metric": "1.6M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7627958872170351893.jpg",
              "description": "Merak Evreni’nde bugün; dışarıdan bakınca \"mahalle abisi\" gibi duran ama içinden \"anaokulu öğretmeni\" çıkan American Bully’leri inceliyoruz!  Sahibinin her türlü şakasına \"eyvallah\" diyen, kedilere masaj koltuğu hizmeti veren ve yavruları dükkandaki plastik oyuncaklara benzeyen bu kaslı beyefendilerin aurası kesinlikle şaka değil! 💪🍼 ​Saldırganlık genleri ayıklanarak tam bir aile köpeği olması için üretilen bu dostlarımızın tek derdi biraz sevgi, biraz da yatış!  #merakevreni #keşfet #doğa #ilginçbilgiler #reels",
              "hook": "This muscular American Bully has a surprisingly gentle demeanor and a 'kindergarten teacher' aura, defying its tough appearance.",
              "format": "voiceover",
              "tier": "HIGH",
              "score": 121.21,
              "video_url": "https://www.tiktok.com/@merakevrenicom/video/7627958872170351893",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7627958872170351893",
              "picked": true
            },
            {
              "handle": "@user162308756",
              "nickname": "Bill1234103",
              "country": "United States",
              "metric": "64K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7628159900539161879.jpg",
              "description": "TikTok team please don't  under review my video #ostviral #2M +#trending #status #mostviralstatus @pktiktokofficial",
              "hook": "A close-up shot of a woman with her eyes closed and her arm raised, showcasing soft lighting and a gentle expression.",
              "format": "pov",
              "tier": "MODERATE",
              "score": 33.88,
              "video_url": "https://www.tiktok.com/@user162308756/video/7628159900539161879",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7628159900539161879",
              "picked": false
            },
            {
              "handle": "@willyya08",
              "nickname": "willyya",
              "country": "Indonesia",
              "metric": "34K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7625956936214646023.jpg",
              "description": "Sikat gigi masih berdarah? Gusi sering bengkak? 😣 Tandanya kamu butuh pasta gigi yang lebih lembut! Herbal Toothpaste formulanya lembut, membantu menguatkan gusi dan mengurangi peradangan. Dengan ekstrak alami, gusi sehat, gigi kuat, nafas segar seharian! #GusiSehat #PastaGigiHerbal #PerawatanGigi #MulutSehat",
              "hook": "Young man demonstrates brushing his teeth with toothpaste, suggesting a solution for bleeding gums and bad breath.",
              "format": "tutorial",
              "tier": "MODERATE",
              "score": 31.35,
              "video_url": "https://www.tiktok.com/@willyya08/video/7625956936214646023",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7625956936214646023",
              "picked": false
            },
            {
              "handle": "@kainattypist26",
              "nickname": "♡︎𝗞𝗔𝗜𝗡𝗔𝗧 𝗧𝗬𝗣𝗜𝗦𝗧♡︎",
              "country": "Pakistan",
              "metric": "308K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7629840556880940318.jpg",
              "description": "please TikTok team don't under review my video@TikTok Pakistan #funnyvideo #funnystatus #foryou #foryoupage #viral #fyp ",
              "hook": "This hilarious video features a cat dressed as a sophisticated gentleman, complete with a turban and vest, casually taking a phone call.",
              "format": "meme",
              "tier": "MODERATE",
              "score": 28.48,
              "video_url": "https://www.tiktok.com/@kainattypist26/video/7629840556880940318",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7629840556880940318",
              "picked": false
            },
            {
              "handle": "@suilaep",
              "nickname": "suil",
              "country": "Portugal",
              "metric": "74K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7630996328889191702.jpg",
              "description": "repost || #rosalina #peach #supermario #supermariogalaxy #movie #aura #edit #fyp #blow",
              "hook": "A magical animated scene shows Princess Rosalina reaching out to a baby Peach, evoking warmth and a sense of gentle care in a dreamlike setting.",
              "format": "other",
              "tier": "MODERATE",
              "score": 23.54,
              "video_url": "https://www.tiktok.com/@suilaep/video/7630996328889191702",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7630996328889191702",
              "picked": false
            }
          ]
        }
      ]
    },
    {
      "key": "paid_ad",
      "label": "Paid Ads",
      "persona_count": 2,
      "generation_count": 15,
      "icps": [
        {
          "name": "Skincare-conscious women aged 18-35 dealing with oily, acne-prone skin and texture issues like visible pores and dark spots.",
          "persona": "Skincare-conscious women aged 18-35 dealing with oily, acne-prone skin and texture issues like visible pores and dark spots.",
          "pains": [
            "stubborn acne marks and scarring",
            "excessive oil and enlarged pores",
            "dull complexion lacking radiance",
            "ineffective products that lack evidence"
          ],
          "scrolls_for": [
            "science-backed skincare routines",
            "before and after transformations",
            "tips for achieving glowing skin",
            "pore-minimizing product reviews"
          ],
          "quote": "I need a routine that actually fades my marks and controls oil.",
          "tags": [
            "clean beauty",
            "k-beauty inspired",
            "dermatologist recommended",
            "beauty",
            "dermatology",
            "acne treatment",
            "indian beauty",
            "pigmentation treatments",
            "skincare routines",
            "sunscreen"
          ],
          "count": 12,
          "videos": [
            {
              "handle": "@L'Oréal Paris",
              "nickname": "L'Oréal Paris",
              "country": "global male grooming",
              "metric": "36.2M",
              "unit": "page likes",
              "cover": "https://scontent-dfw6-1.xx.fbcdn.net/v/t39.35426-6/705949613_915846214847812_4714218692251855247_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=5zq0IhrwK6kQ7kNvwHwAbDY&_nc_oc=AdqkkdPixcrR7GtH_TfDP5Yyo4_mvu4DMbb0X-wiLq9-DU3G4WKK1W6UgnZiJNbnZwg&_nc_zt=14&_nc_ht=scontent-dfw6-1.xx&_nc_gid=QkJKTyevJ7u3-Gf1rngMpw&_nc_ss=72289&oh=00_Af-ETIdWkIdRu1AXQvSY117vpXXn5WlGw7jOBAY-km-org&oe=6A354C89",
              "description": "{{product.brand}}",
              "hook": "The video starts with the provocative question 'Still using soap?' to challenge traditional grooming habits.",
              "format": "voiceover broll",
              "tier": "AD",
              "score": 36184263,
              "direct_video": "https://video-dfw5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQOpDHgIV64elSmL0cyPLUBRZjPRNkwdYDZquV-iLzqixc4G0UgDm1obHv5Jai35LqZf8aJbZouScb03Hpl6VrQmTaNTu5xcftBzMeCwhc2MbQ.mp4?_nc_cat=111&_nc_sid=b66105&_nc_ht=video-dfw5-1.xx.fbcdn.net&_nc_ohc=L-Ja_XRmC9wQ7kNvwG--UXs&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjIzNzgyODcwMzI2NTk2OTksImFzc2V0X2FnZV9kYXlzIjoyMCwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=38de9f6a9618d572&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC81RjRGM0Y3Q0JDM0JFMkY4NEQ5NEM5QkFDNTBBODQ5Ml9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50L0Y2NEI4RDYyRjM1NTU2MUJGQzgyMUI2OTZCRUU4NkExX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbmu4ucw8K5CBUCKAJDMywXQBgAAAAAAAAYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=QkJKTyevJ7u3-Gf1rngMpw&_nc_ss=72289&_nc_zt=28&oh=00_Af-6r6QnjtYJPJ7dW_JgEgJKaJzgdjIeX0S0Cr8OweXPNQ&oe=6A3550DD",
              "video_url": "https://www.facebook.com/ads/library/?id=1270929275251217",
              "platform": "paid",
              "embed_url": "",
              "picked": true
            },
            {
              "handle": "@Kriti Sanon",
              "nickname": "Lets Hyphen",
              "country": "india",
              "metric": "14M",
              "unit": "page likes",
              "cover": "https://scontent-phl2-1.xx.fbcdn.net/v/t39.35426-6/542605461_1811160163127822_4566237441667751140_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=_9GZkWl46vYQ7kNvwEZWhDr&_nc_oc=AdpnylWltQKmyWU_nptwPpvfpT8OLKNGYVDWAf0hq3tcDYWi306Ij2gSTG5weLvXtBo&_nc_zt=14&_nc_ht=scontent-phl2-1.xx&_nc_gid=sAdt17NGggJaalcLsoyj1Q&_nc_ss=72289&oh=00_Af-d-HZAG6zDo_saati4xhLcZnxgzGRH0tVHzU5m2ZklkQ&oe=6A356A2D",
              "description": "All I Need Sunscreen SPF 50 PA++++🫶🏻✨\nEver since i started my skincare journey, I never ever compromised on SPF. And for HYPHEN, we had to create something that hyphens moisturization with sun protection and goes even further, targeting sunspots and blue light damage.\nToo much to ask for? Well, say HELLO to the All I Need Sunscreen SPF 50 PA++++ - your ultimate sun-shield that protects from UV damage as well as blue light. 🌞\nIt is very lightweight, fragrance-free and leaves no white cast. All I Need Sunscreen truly lives up to its name - it's all YOU need in a sunscreen. Hyphen it into your routine now at letshyphen.com!\n\nIn this sunscreen we have HYPHENED 7 super-powerful ingredients like:\n\n➖ Kakadu Plum: Brightens your skin\n\n➖ Niacinamide: Reduces Pigmentation\n\n➖ Kojic Acid: Reduces sun-spots\n\n➖ Ceramides: Rebuild & strengthen skin’s barrier\n\n➖ Hyaluronic Acid: Deeply hydrates\n\n➖ Vitamin E: Protects from UV damage\n\n➖ Aloe Vera Extract: Prevents water loss from skin\n\nHead to letshyphen.com to HYPHEN us into your daily life!\n\n#Hyphen #LetsHyphen #HaveItAll #HyphenItAll #NewBeginnings #Skincare #AllINeedSunscreen #Sunscreen #SunShield #Hydration #SkincareEssentials #NewLaunch #CleanBeauty #VeganSkincare #PetaCertified #SustainableBeauty",
              "hook": "The video opens with a well-known celebrity holding a product and saying she is going to explain how they 'hyphen' the sunscreen.",
              "format": "talking head",
              "tier": "AD",
              "score": 13999005,
              "direct_video": "https://video-phl2-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQNj_F3aQgJdBsJ8vE-OA5iM-CPLxiLFLwds5m1rNiCmlMB1dnNXbDok4gm0d08QrxCFdGXk_b8Vc8h8VwNo9zyh-8n2CeKpyAUuAzJooEyaVA.mp4?_nc_cat=111&_nc_sid=b66105&_nc_ht=video-phl2-1.xx.fbcdn.net&_nc_ohc=xVs7hgIrgGUQ7kNvwHUy2JQ&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjcwNjYyNDY5ODAxMzk5NDgsImFzc2V0X2FnZV9kYXlzIjo4MzIsInZpX3VzZWNhc2VfaWQiOjEwMTAxLCJkdXJhdGlvbl9zIjo1MiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=e28a5aa12009da39&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9CMjRDODVCRUI3RDU2RUZGMkE3N0E3Mjk2MzY0M0VCQl9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dIRGNzUm1HSXo4TEx6MEJBTFN3ejhySHlOb3ZidjRHQUFBRhUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbY7qvS2q2NGRUCKAJDMywXQEomZmZmZmYYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZeqdAQA&_nc_gid=sAdt17NGggJaalcLsoyj1Q&_nc_ss=72289&_nc_zt=28&oh=00_Af_korq0np0ycV5WdlW1qPFP4TWYZEPJOsFIT0JZzZtsEw&oe=6A3554D1",
              "video_url": "https://www.facebook.com/ads/library/?id=785414371102053",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Vichy",
              "nickname": "Vichy",
              "country": "middle east",
              "metric": "9M",
              "unit": "page likes",
              "cover": "https://scontent-dfw6-1.xx.fbcdn.net/v/t39.35426-6/702589966_1666247691289847_1634108470013341881_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=uLX-24ro9BAQ7kNvwG4_LaC&_nc_oc=AdoafeMkpWcFmRN1SeCvGJ9liNTUvzfRsRjfkq9WUoV_z9EnrEoZghAK2HUYmpyt8y8&_nc_zt=14&_nc_ht=scontent-dfw6-1.xx&_nc_gid=3VH-FQ8cgVTSYXpzUwfowg&_nc_ss=72289&oh=00_Af810ajZYa-VZiW8URBz6Ceb0uo3phxCR2lrmT-Im7fLRA&oe=6A355D1B",
              "description": "Oily skin struggle? Ultimate two-step routine for your oily skin ✨\nCleanse with Normaderm cleanser and protect with Capital Soleil Dry Touch SFP50 sunscreen \nبتعاني من مشاكل البشرة الدهنية؟ روتين من خطوتين بس لبشرتك الدهنية ✨\nغسول نورماديرم للبشرة الدهنية وواقي الشمس كابيتال سولاي Dry Touch SPF50\n#VichyEgypt #VichyNormaderm #MevsAcne #skincare #acne #VichyDryTouch",
              "hook": "The video opens with the Vichy logo and Arabic text introducing the ideal summer routine for oily skin.",
              "format": "demo",
              "tier": "AD",
              "score": 8984064,
              "direct_video": "https://video-dfw6-1.xx.fbcdn.net/o1/v/t2/f2/m367/AQOl_2g2KZY3CpG1Kp0AcpsqI85pYtKCCz7o_rjdeC8F4vK_R-9meu8dDafhAgHfe90ZCVaUBx6HSIhB0XttME3l-zIZPr3K-kpYGYqLMg.mp4?_nc_cat=103&_nc_sid=ef5aa3&_nc_ht=video-dfw6-1.xx.fbcdn.net&_nc_ohc=V0A8TqupDz0Q7kNvwHMm3yo&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLnByb2dyZXNzaXZlX2gyNjQtYmFzaWMtZ2VuMl83MjBwIiwieHB2X2Fzc2V0X2lkIjoxNzkyOTM2MzUzOTQwNzIzMywiYXNzZXRfYWdlX2RheXMiOjI3LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6NiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&_nc_gid=3VH-FQ8cgVTSYXpzUwfowg&_nc_ss=72289&_nc_zt=28&oh=00_Af8FKhhS3VPSa1I3n6FrLZcniwpJG0lYreeeF01mb6HJ4g&oe=6A355BDB",
              "video_url": "https://www.facebook.com/ads/library/?id=912910051764862",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Eucerin",
              "nickname": "Eucerin",
              "country": "uk",
              "metric": "4.8M",
              "unit": "page likes",
              "cover": "https://scontent-mia3-3.xx.fbcdn.net/v/t39.35426-6/690913348_1306320351714303_6158952715292093599_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=_wvpwu0jeJAQ7kNvwFJHxp5&_nc_oc=AdreGrugKIzZY9oShu9wClGVGTAVZD7LLOQq0lOxC__5cO8uoIKymUIn6p1sRQp_n64&_nc_zt=14&_nc_ht=scontent-mia3-3.xx&_nc_gid=wNQQR-XwVSGu6zHZxAcPPA&_nc_ss=7d289&oh=00_Af_0XUgcO3-_vh6YyxHBH42u1X6nc3pO1MwiisSTSirPYw&oe=6A35493D",
              "description": "{{product.brand}}",
              "hook": "A high-end product shot of the Dermopure Clinical Purifying Cleanser is shown with splashes of water.",
              "format": "talking head",
              "tier": "AD",
              "score": 4847879,
              "direct_video": "https://video-mia5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQM62m5YUyr_hRPEOoRwRLnz_Ba1aInG5RMk6jk3Ceb6iTkxdnx2-m8ozOduNvOS17ACE9AjV3Kv_ii2YQo3JyxPG-X_cvgniDbiJN2p48Xwkg.mp4?_nc_cat=102&_nc_sid=b66105&_nc_ht=video-mia5-1.xx.fbcdn.net&_nc_ohc=Kow1Febpt-0Q7kNvwG8PyuB&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjEyODk5MDc4ODY0Mzg3NDEsImFzc2V0X2FnZV9kYXlzIjo1NCwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=49eb3e05dbe21523&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9DOTRDQ0FCQ0I2QkY0MDgwMkYwMjJFMjg0MjY1Mzc5M19tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzkwNEIzMTlFNjJGM0RGNjU4MTc3RDM4OTUwNkEyODhBX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaq5enVwsrKBBUCKAJDMywXQBgAAAAAAAAYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=wNQQR-XwVSGu6zHZxAcPPA&_nc_ss=7d289&_nc_zt=28&oh=00_Af98n83Or8OU4VxHDR4XHSPW9z35iMISaQpwXiLiNeUSvA&oe=6A3578A2",
              "video_url": "https://www.facebook.com/ads/library/?id=972380778876909",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Cetaphil",
              "nickname": "Cetaphil",
              "country": "global",
              "metric": "4.1M",
              "unit": "page likes",
              "cover": "https://scontent-dfw6-1.xx.fbcdn.net/v/t39.35426-6/646620921_1284511976935133_9166193244315346589_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=lZ3EyqA87zMQ7kNvwGavtFq&_nc_oc=Adoe3BxzkZNbh51iG3b63iXhdLdqOYaJ8bOh3Tvi6zbNRpzNA_ZKxdA4xNc9qL-8070&_nc_zt=14&_nc_ht=scontent-dfw6-1.xx&_nc_gid=QkJKTyevJ7u3-Gf1rngMpw&_nc_ss=72289&oh=00_Af8lbrxH46yXTLDNKZxYkvj-J4eNd1bqzWx6WJU0MccxJQ&oe=6A355BDE",
              "description": "Non-stripping cleanser. Everyday moisturizer.\nBuilt for sensitive skin.\nShop now.",
              "hook": "Upbeat hip hop music plays as Cetaphil bottles transition rapidly with bold text overlays like 'NEW ERA'.",
              "format": "voiceover broll",
              "tier": "AD",
              "score": 4061068,
              "direct_video": "https://video-dfw5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQNbwV938Cu_jI7iCoIYAfEV7twujdQhEiD6jnuoC1GZDcyASlp3vKWCmjnUhuddJ2nYmRKwgBhrORALeBmamt4gPEvyd7ZnLnoLYK-maLp1LQ.mp4?_nc_cat=111&_nc_sid=b66105&_nc_ht=video-dfw5-1.xx.fbcdn.net&_nc_ohc=lYGvF8sTRskQ7kNvwFccuYK&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjQyNjExNTM0NjQxMzg3NTIsImFzc2V0X2FnZV9kYXlzIjoxMDQsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjoyOSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=877967d3f76f41be&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC84ODQzMzRCNzJCMUNFMjA0Rjg3MDNENzk2OUZGODNCNF9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50L0ZENEFEQUU5QjA4MzY2NjgzMzk5NDgwMEI3Qjc1MDgxX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaA8IGp49-RDxUCKAJDMywXQDz-uFHrhR8YGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=QkJKTyevJ7u3-Gf1rngMpw&_nc_ss=72289&_nc_zt=28&oh=00_Af8huiNfM4u71DKx3UO6tAuCl8KD5cR1bf0keWbaN0jHkg&oe=6A3554C9",
              "video_url": "https://www.facebook.com/ads/library/?id=1266703455423800",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Nykaa",
              "nickname": "Nykaa",
              "country": "india",
              "metric": "3.5M",
              "unit": "page likes",
              "cover": "https://scontent-dfw5-2.xx.fbcdn.net/v/t39.35426-6/546916836_642697201869492_7992179752784304751_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=wJjjkTXFxdkQ7kNvwGn05oB&_nc_oc=AdqeTLHG_VJIuKKP9K9juuC8jC3J5lDVfIZhOeX03cTIOG21rl830FMWajm43JpE9j0&_nc_zt=14&_nc_ht=scontent-dfw5-2.xx&_nc_gid=3VH-FQ8cgVTSYXpzUwfowg&_nc_ss=72289&oh=00_Af_d_eSFinhy19kcsYflqGnc42iV9lcdPPAIGLdilExWHg&oe=6A356573",
              "description": "Fresh drops, endless beauty ✨Upgrade your beauty game with the hottest launches TODAY! Shop Now at Nykaa 🛍️",
              "hook": "The creator claims a new product on Nykaa was good enough to break her long-standing loyalty to other brands.",
              "format": "tutorial",
              "tier": "AD",
              "score": 3450074,
              "direct_video": "https://video-dfw5-2.xx.fbcdn.net/o1/v/t2/f2/m366/AQPaOvtU-CWaLDQfhJzKYsf9QFB3fLqN1WLilUm0nrSXKCCVB1xDLaIkFjGn1o11tnojIf2ooFKbXrMrtN3Cb016YNmLsFqrHUYpwJzkEcObmA.mp4?_nc_cat=107&_nc_sid=b66105&_nc_ht=video-dfw5-2.xx.fbcdn.net&_nc_ohc=eLFu83Xrkb0Q7kNvwFwya0o&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjQyMzYwMDY1OTY2Njk3NDEsImFzc2V0X2FnZV9kYXlzIjoyNzcsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjo3OSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=cbe07c9131728ffc&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9FMjRCNzY3QzZENjVCQThGRTI4Mzk1QTQ2QUY1RTk4RV9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzM4NEEzOTkxOTlBNEM1M0I5QTZEQkUyQTI0OTNDNEJBX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbaxK_HhKiGDxUCKAJDMywXQFPmZmZmZmYYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=3VH-FQ8cgVTSYXpzUwfowg&_nc_ss=72289&_nc_zt=28&oh=00_Af9CWHxbuU19eSPLsRpabSHsE1dUcnQCUDR41foFMy8otw&oe=6A357719",
              "video_url": "https://www.facebook.com/ads/library/?id=1568542287848380",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@BEARDO for Men",
              "nickname": "BEARDO for Men",
              "country": "india",
              "metric": "2.4M",
              "unit": "page likes",
              "cover": "https://scontent-iad6-1.xx.fbcdn.net/v/t39.35426-6/678967359_1609925153632664_5273274332359390299_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=3_oYjeLl1boQ7kNvwG3orV_&_nc_oc=AdrFtxphpa5XPM08vfnoFaQ4aWy-tohM4WISa65yGdvw-baRbRGeF1OmV6Pk4n7djmM&_nc_zt=14&_nc_ht=scontent-iad6-1.xx&_nc_gid=hvAS6X9uxAS14su7cFpZLg&_nc_ss=72289&oh=00_Af8-SnYpkA2o47wiwUZSa_5vTqMV4GZ4WI95BR2uGbTPEw&oe=6A357009",
              "description": "Summer skincare sorted — 7 products, one kit, ₹999 only.Face wash, sunscreen, body wash, moisturizer… everything you actually need to step out without worrying about the sun wrecking your skin.Most guys spend more on one product. This gets you the entire routine.",
              "hook": "A man points to a ₹999 price tag displayed over a collection of seven premium grooming products.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 2399832,
              "direct_video": "https://video-iad6-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQOowf8-EgOmdu2rZ6BLwWpsX98YNQmOUyDH1qyOz4vcK0fTZmoPgQRezfH-zMZnUahctGkw80UPBZuJD8abbg7yTBYphsTThUweSrbYRvDLwg.mp4?_nc_cat=100&_nc_sid=b66105&_nc_ht=video-iad6-1.xx.fbcdn.net&_nc_ohc=rTTW1d60L4AQ7kNvwGrfrV5&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjEyNDU5NDAzMDc3MDEzODIsImFzc2V0X2FnZV9kYXlzIjo3MiwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjM2LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=b4bbb8bbb125394e&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC84RjQ0M0M2ODEyMTgxMkFBMDlGQjA5QkY3NDVGOUVCQ19tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzdDNEMxRUY1REE5MDgwN0E0MjIzMkM2OEFGNkY5NDg4X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaMup3Xosu2BBUCKAJDMywXQEJu2RaHKwIYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=hvAS6X9uxAS14su7cFpZLg&_nc_ss=72289&_nc_zt=28&oh=00_Af9po4z7qjcCxSNv4wdy0tiSqdSntZGXSpWg7-dWFQTvuA&oe=6A354B80",
              "video_url": "https://www.facebook.com/ads/library/?id=927282413403005",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Garnier Men India",
              "nickname": "Garnier Men India",
              "country": "india",
              "metric": "2.1M",
              "unit": "page likes",
              "cover": "https://scontent-mia3-1.xx.fbcdn.net/v/t39.35426-6/722147768_1947441072603152_7507417174048805192_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=cxhmyAn0_XgQ7kNvwEjtkIe&_nc_oc=AdqOftYYQWbmbHVBt-pxi9_f7_OmH_1ZBdteAFvaTXhyqAnoQ2OLwrmKWwNcRRcR-Cg&_nc_zt=14&_nc_ht=scontent-mia3-1.xx&_nc_gid=wNQQR-XwVSGu6zHZxAcPPA&_nc_ss=7d289&oh=00_Af8KdxcrmOijwMk73916JGw4dF_xBqu61N-dhCVFQgJ87g&oe=6A354F18",
              "description": "{{product.brand}}",
              "hook": "A CGI visual of a product capsule dissolving into liquid followed by two men with clear skin.",
              "format": "voiceover broll",
              "tier": "AD",
              "score": 2062475,
              "direct_video": "https://video-mia5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQMOne1z9m8dA52UaMSUnDJ6ecIwRRwNPuJ2xqt2mzgkjBDATvdb3pBwP9pnJzHoVg-Au2IjhtawQyEG6gTDbICwNAK9XCuFvxGeBiLMKDL08g.mp4?_nc_cat=104&_nc_sid=b66105&_nc_ht=video-mia5-1.xx.fbcdn.net&_nc_ohc=IfvRGaSt7NMQ7kNvwED8Eun&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjE1Mzk5NDY5MzQyMzU5NzUsImFzc2V0X2FnZV9kYXlzIjo2LCJ2aV91c2VjYXNlX2lkIjoxMDc5OSwiZHVyYXRpb25fcyI6NiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=8ef165a128ff24ea&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9EQjRCRjY4OUY0RUEwRDExQkIxNTNENkQ3RjlFQzFBN19tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzBBNDA4OTcwODQ0N0Q4QzQzRTg4RjQ5RDA3NEMxNjk2X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaOzeff2qS8BRUCKAJDMywXQBgAAAAAAAAYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=wNQQR-XwVSGu6zHZxAcPPA&_nc_ss=7d289&_nc_zt=28&oh=00_Af9c4kiYo20ryjd33U6sDKIZdscASdCMJzZsYKgTzGjAww&oe=6A354C58",
              "video_url": "https://www.facebook.com/ads/library/?id=995307846754129",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Garnier Men India",
              "nickname": "Garnier Men India",
              "country": "india",
              "metric": "2.1M",
              "unit": "page likes",
              "cover": "https://scontent-mia3-3.xx.fbcdn.net/v/t39.35426-6/722132993_1334924778597944_2111010268397907753_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=Wei9BOfBmwAQ7kNvwF8TtHb&_nc_oc=Adr6Hxzls_9PsIXhWnJ3kYpxe5HJ5GK6pOUnQaTaz0oztgkS6hmNKNjo4I2q2P3wpdU&_nc_zt=14&_nc_ht=scontent-mia3-3.xx&_nc_gid=1WrkIgkQnTkN2T0aGcC-lw&_nc_ss=7d289&oh=00_Af9SMCR5fGfnaR_2Bik0crF6PzXh372FDhN3mXC35Mh0DA&oe=6A355004",
              "description": "{{product.brand}}",
              "hook": "A close-up of a face with acne featuring a graphic showing 99% pimple-causing germs being eliminated.",
              "format": "voiceover broll",
              "tier": "AD",
              "score": 2062475,
              "direct_video": "https://video-mia5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQM119VnE1UefuAoFsKzrNSta-ePw5PgHh4rehT5oEk1PQYW2OPkv-qzhrcV1sWJu4O0kRTHss_KsN5gEqdayJ7PainJAWwPkEnWeLAYJyhgXg.mp4?_nc_cat=101&_nc_sid=b66105&_nc_ht=video-mia5-1.xx.fbcdn.net&_nc_ohc=tFnE8pyAhRoQ7kNvwEY4dXb&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjg1ODE2NDAxMzUwNzcxNSwiYXNzZXRfYWdlX2RheXMiOjYsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjo1LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=82b818cd2f1cb5a3&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC85NDRGQzdGRjdFNUI2NDYwRTg3NDBGRUM4OUIxOTg4Ml9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50L0E0NEEzQkNCNDNFQ0UyNDczOEJCNzY3OTlCQTFGNDg0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaGkvmS3J-GAxUCKAJDMywXQBfXCj1wo9cYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=1WrkIgkQnTkN2T0aGcC-lw&_nc_ss=7d289&_nc_zt=28&oh=00_Af84wZOwrzMdpQaYckO_baA5YHOA_d0WSY_UXPVDapbzCQ&oe=6A355DC3",
              "video_url": "https://www.facebook.com/ads/library/?id=988057523966017",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Rohit Sachdeva",
              "nickname": "Chemist At Play",
              "country": "india",
              "metric": "1.8M",
              "unit": "page likes",
              "cover": "https://scontent-bos5-1.xx.fbcdn.net/v/t39.35426-6/574322312_1190258763005896_6875550377619206176_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=cDxK_vOdDaUQ7kNvwGFsfVT&_nc_oc=Adr26c9MSwUdkaHefIWfWnZxqkxfb6VVeFbLgKsnCPM68HqB6MY6JZcv37UImQ2zH2c&_nc_zt=14&_nc_ht=scontent-bos5-1.xx&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&oh=00_Af-b1Qeo3L-w7CJ4YUV-0mhvyTC0YIhZ71sG-0Jt8d46LQ&oe=6A356867",
              "description": "Blackheads, Whiteheads & Tan Removal Treatment \n\nFor Buying Link Comment YES or Check Bio✅\n\n#rohitsachdeva #beautyhacks #beautytips #beautyinfluencer #trendingbeautytips #viralbeautytricks #viralbeautytips #skinwhitening #glassskin #clearskin #clearskinsecrets #glassskinchallenge #glassskincare #darkspots #homeremedies #glowingskin #glowmask #hydratedskin #healthyglowingskin #viralshorts #musttrythisathome #trendingshorts #trendingshort",
              "hook": "A man demonstrates a face scrub with a text overlay stating 'NOT AN ORDINARY SCRUB'.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 1790399,
              "direct_video": "https://video-bos5-1.xx.fbcdn.net/o1/v/t2/f2/m86/AQPMVbV2mcVW1EQWDymw4LDvNqjJxsaNeUqyBOoSPU6qzc4sMU0AtFMUUTIPNu6FeTTUvA4Hk1XKEfEBCwUAx036w-OZXH54TRBkFRw.mp4?_nc_cat=107&_nc_sid=b66105&_nc_ht=video-bos5-1.xx.fbcdn.net&_nc_ohc=sDGARnZn7IgQ7kNvwGPzOzF&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTMxNDc1OTI4MDE4Mjc1NywiYXNzZXRfYWdlX2RheXMiOjI3MCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjYwLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=d4a3b6381681e0d8&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FNTQ3RTc3NDk1Njc1NzYyNjA2NkU3M0FCMTNBMTVCOV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC83NzYzMDE1OTUyNjE4NjNfMzg0OTgyNDc1MTk1ODU2NDQ0OC5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmypfi_Yfx1QQVAigCQzMsF0BOXdLxqfvnGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAZeadAQA&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&_nc_zt=28&oh=00_Af9swYSCIAuXuFWiC04PI76hfYPocriG2kGXOGwjK_6hTA&oe=6A3162E4",
              "video_url": "https://www.facebook.com/ads/library/?id=1506578723907528",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Rohit Sachdeva",
              "nickname": "Foxtale",
              "country": "india",
              "metric": "1.8M",
              "unit": "page likes",
              "cover": "https://scontent-iad3-2.xx.fbcdn.net/v/t39.35426-6/656963912_1137729265107143_6381821848479913921_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=DaPiqIgty0IQ7kNvwFoFlgZ&_nc_oc=Adp_OMjcSpgoA6m1j5kAyETpk3VimIIkho3sCgLchreVR2E1Y6ZmJV5N-tsiIkQEphg&_nc_zt=14&_nc_ht=scontent-iad3-2.xx&_nc_gid=-fM1w7ia6n4BkYJbJFqSiw&_nc_ss=72289&oh=00_Af8UsMSOTGYlhGyk-x3VUEdv-bJKCrakDu_dPhpFlVhfcQ&oe=6A356259",
              "description": "Best D-Tan for Skin Whitening & Tan Removal: Instant Glowing Skin\n\nFor Buying Link Comment YES✅\n@foxtaleskin \n#rohitsachdeva #skinwhitening #foxtaleskin #glowingskin #tanning",
              "hook": "मात्र दस मिनट में हटाना है सारा टैन और डलनेस",
              "format": "talking head",
              "tier": "AD",
              "score": 1790399,
              "direct_video": "https://video-iad6-1.xx.fbcdn.net/o1/v/t2/f2/m367/AQN3uzaPktV722whcg4aCWISmcOKHyQrkMMqS944XB_1Xro-YD7htEahK-hUnlaUfFombZl1Ld8KxAPzFHQFcn1XfIZNvekO3xWe8nzWYg.mp4?_nc_cat=100&_nc_sid=ef5aa3&_nc_ht=video-iad6-1.xx.fbcdn.net&_nc_ohc=hqWGyt4_PXcQ7kNvwGMOzkb&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLnByb2dyZXNzaXZlX2gyNjQtYmFzaWMtZ2VuMl83MjBwIiwieHB2X2Fzc2V0X2lkIjoxNzk0OTc3MjE3MDEyMDU4NywiYXNzZXRfYWdlX2RheXMiOjgyLCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6NjMsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=-fM1w7ia6n4BkYJbJFqSiw&_nc_ss=72289&_nc_zt=28&oh=00_Af9ZJhUdRYF2LpMEifJ4olZMyNzNFDEffhcP6GV9BdKkZQ&oe=6A356FC2",
              "video_url": "https://www.facebook.com/ads/library/?id=1246577917627897",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Aveeno",
              "nickname": "Aveeno",
              "country": "global wellness market",
              "metric": "1.7M",
              "unit": "page likes",
              "cover": "https://scontent-mia5-2.xx.fbcdn.net/v/t39.35426-6/526914278_775239301631086_4108392969239299050_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=RSvGczx1efgQ7kNvwHYGRxb&_nc_oc=AdrM594o8daG1E_JEAq_pPH0ltMJvAjLlXOZhjslc2K0i33D7LeQIcMjr6KwDlEax9U&_nc_zt=14&_nc_ht=scontent-mia5-2.xx&_nc_gid=1WrkIgkQnTkN2T0aGcC-lw&_nc_ss=7d289&oh=00_Af9g1qRJBx_uSQKs-wdNkCaVMRuLDEU-p0At3-6QWzS4Ow&oe=6A356CF2",
              "description": "Spend a summer day with us At Home With Aveeno & @drewomaukeleghe 🤍 we chat all things wellness, advice for your younger self and of course, our Calm+Restore Moisturising Lotion SPF 50 ✨ summer skincare + SPF…..always ✔️",
              "hook": "A close-up shot of skincare products on a wooden tray followed by a woman inviting the viewer into her home.",
              "format": "talking head",
              "tier": "AD",
              "score": 1712115,
              "direct_video": "https://video-mia5-2.xx.fbcdn.net/o1/v/t2/f2/m412/AQM2wqiG3yTtNTKTP0r-RE-pQfMuebmGtAZ9o3lFcE-s4z41N9PjOq8KrfSDtQWfpTf6Mp3wS1YYJFXn4RNGNoM.mp4?_nc_cat=100&_nc_sid=ef5aa3&_nc_ht=video-mia5-2.xx.fbcdn.net&_nc_ohc=ioeK0nVfF-IQ7kNvwHCM6lj&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmFzaWNfaHEyX2hkX3Byb2dyZXNzaXZlIiwieHB2X2Fzc2V0X2lkIjoyNTQ4MjE1NTIyODA0ODQ5MywiYXNzZXRfYWdlX2RheXMiOjIyMiwidmlfdXNlY2FzZV9pZCI6MTA2ODAsImR1cmF0aW9uX3MiOjYwLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&_nc_gid=1WrkIgkQnTkN2T0aGcC-lw&_nc_ss=7d289&_nc_zt=28&oh=00_Af8C1N9xMT8m5FtDRHNB_mUXiummbyGYmaa1H5L29oQsBQ&oe=6A35634E",
              "video_url": "https://www.facebook.com/ads/library/?id=1121585783149261",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            }
          ]
        },
        {
          "name": "Women aged 18 to 45 who are conscious consumers seeking natural and ethical solutions for hair thinning and scalp health.",
          "persona": "Women aged 18 to 45 who are conscious consumers seeking natural and ethical solutions for hair thinning and scalp health.",
          "pains": [
            "Visible hair fall and thinning",
            "Chemical-heavy hair products",
            "Loss of hair volume",
            "Slow regrowth cycles"
          ],
          "scrolls_for": [
            "Natural hair growth remedies",
            "Clean beauty ingredient breakdowns",
            "Sustainable hair care routines",
            "Scalp health transformations"
          ],
          "quote": "I want thicker hair using products that are actually good for me.",
          "tags": [
            "clean beauty",
            "hair growth",
            "ethical sourcing",
            "ayurvedic beauty",
            "hair loss prevention",
            "ugc creator",
            "herbal beauty",
            "ayurvedic haircare",
            "natural living"
          ],
          "count": 3,
          "videos": [
            {
              "handle": "@Aveda",
              "nickname": "Aveda",
              "country": "hair loss and eco-conscious beauty",
              "metric": "2.1M",
              "unit": "page likes",
              "cover": "https://scontent-bos5-1.xx.fbcdn.net/v/t39.35426-6/671603246_1163667299151740_6907598772460307021_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=V4PsMNI5DxMQ7kNvwE4XqUX&_nc_oc=AdooUm9UHUVjL5-1NvnR_xW64O9_pxHuXAUoeSnirDPcTlnSvYAhmXjtluMtBMBWTFc&_nc_zt=14&_nc_ht=scontent-bos5-1.xx&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&oh=00_Af81UtXiyt7vhX1ptr4w7UFUB-6CTw5Kxi-U9yNVoPtwAw&oe=6A356A8C",
              "description": "{{product.brand}}",
              "hook": "A shot of several purple Aveda hair care products on a white textured background with text overlay 'Intentional sourcing'.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 2131152,
              "direct_video": "https://video-bos5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQMuyVIXQHJ5Mh4e4QP5eaF6Z-nDrMZZdW957bUMTKTmkoDzFps45lv_za4pgRX8JA_mXs6rGS-Zo29ayPRrsyzNzgKfSTJFFD-WYNk4wQ4sgA.mp4?_nc_cat=101&_nc_sid=b66105&_nc_ht=video-bos5-1.xx.fbcdn.net&_nc_ohc=F8R1FKlWT8cQ7kNvwHy4cZz&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjIxNTQ2NDQwNjg2NjcxNjAsImFzc2V0X2FnZV9kYXlzIjo2MiwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjE4LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=bd04e270f034e076&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9ERDQwRkVCOTI1QzFEQjU4OENBNjA0Nzg4Q0ZEMTFBRl9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50L0ZCNEUxMTQ4MjFFM0NBMjNFNDE1OTlBNkNBOUI5RkFDX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACawvKSl5ejTBxUCKAJDMywXQDLXCj1wo9cYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&_nc_zt=28&oh=00_Af8Jxqtigt7vFScfOOKQcfUlLh1_VPl-0618zszwDEv1gg&oe=6A35441B",
              "video_url": "https://www.facebook.com/ads/library/?id=1267287285530211",
              "platform": "paid",
              "embed_url": "",
              "picked": true
            },
            {
              "handle": "@Blossom daily",
              "nickname": "Plix",
              "country": "india",
              "metric": "39K",
              "unit": "page likes",
              "cover": "https://scontent-phl2-1.xx.fbcdn.net/v/t39.35426-6/639697847_1609045923679203_6376268943534587892_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=vJIPG94yCqMQ7kNvwHrRh3l&_nc_oc=AdrCnl-Z6LXCbOV0zC__OrMBkNmP1Bx0F_e171Jvtd78xEkNi5AlodfBgHTo40lWV20&_nc_zt=14&_nc_ht=scontent-phl2-1.xx&_nc_gid=Q_Z_hhTuef6lOhUN4vm8wQ&_nc_ss=72289&oh=00_Af_Q8ZlI8ZlU7NU1ZmNoYHPtXiGbhl8oLRPrz60gDi2X4A&oe=6A35462A",
              "description": "Comment for link\nPlix Rosemary Hair Growth spray \n#viral #trending #skincare #instagram #blossomdaily__",
              "hook": "The video starts with a close-up of the Plix Rosemary hair growth spray against a natural tree background.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 38994,
              "direct_video": "https://video-phl2-1.xx.fbcdn.net/o1/v/t2/f2/m69/AQOKbSgJiGRwV6vbvk9vYgj9fCG_rIPRb-pZ3AKaxQFN3oQaTgfR2T3figolx1nBJrPAfOzW_OfTSxXwDt4f-4FF.mp4?strext=1&_nc_cat=108&_nc_sid=b66105&_nc_ht=video-phl2-1.xx.fbcdn.net&_nc_ohc=occOkv3XhFAQ7kNvwHi8yEH&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc4NjM3MzA5MTM1NjMwMDksImFzc2V0X2FnZV9kYXlzIjoxNDMsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoyNywidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=ad468e85c55ce9d4&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HRkstMlNTcjJvYW1TT0FQQUlLUjJ4OU5lYUY2YnNwVEFRQUYVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzJCNDhFNjlGRDU5QzQzRjc3RDFEQTAwRURFRThDN0I3X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaCxrr3_r27PxUCKAJDMywXQDuIcrAgxJwYEmRhc2hfYmFzZWxpbmVfMV92MREAdQBl5p0BAA&_nc_gid=Q_Z_hhTuef6lOhUN4vm8wQ&_nc_ss=72289&_nc_zt=28&oh=00_Af-mx9jYHXFk2wUkYOTkSHJrbSwDJFzuHcrHmpWdLSfXHw&oe=6A355F2E",
              "video_url": "https://www.facebook.com/ads/library/?id=26391404540445538",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Pureusofficial",
              "nickname": "Pureusofficial",
              "country": "india",
              "metric": "20K",
              "unit": "page likes",
              "cover": "https://scontent-bos5-1.xx.fbcdn.net/v/t39.35426-6/545550722_1454665818915327_1599429280797944067_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=meTygx14nigQ7kNvwH9ExVk&_nc_oc=AdqR1RDz3QmHeyJkLUzSa4F7ZM6aaHrKjG7emETJRVLoLoqsOt-8b3TZpDeOfYsM8a4&_nc_zt=14&_nc_ht=scontent-bos5-1.xx&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&oh=00_Af_DLC7m5CsCwV490MJ4p8B0jZdoJi8scRpO4k_LRDDgPA&oe=6A357823",
              "description": "{{product.brand}}",
              "hook": "A woman opens a package and expresses immediate regret for not trying the product sooner.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 19673,
              "direct_video": "https://video-bos5-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQPR4HM_aH8XuA781YB2KXNIAq0nWpy5yMxO--ZsiKy9XrnZjEtaaaqVWHem5XHrrsQ6tTelr6ELEYeusWINHw2OtBKcVV224q7k0UgxQU9NFw.mp4?_nc_cat=105&_nc_sid=b66105&_nc_ht=video-bos5-1.xx.fbcdn.net&_nc_ohc=cjjy_Ma5wr8Q7kNvwGS-wU_&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjE3MzM0Mjk2NzA4NjgxODcsImFzc2V0X2FnZV9kYXlzIjoyNzgsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjozOCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=69cbad904878ba50&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9DNzRCRDY3QjYwMTM5MjY4QkUwRDEwNUMwMEM1Nzc5RV9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzAyNEIxOTA3MzMxRUUwNzhBQjYwRjc5MUExRkM1NEFCX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACa207O88aKUBhUCKAJDMywXQENaPXCj1woYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=L3YhZkhXffteAUJGlXMnGA&_nc_ss=72289&_nc_zt=28&oh=00_Af9tO5tYEekoNRGBi24ZK6KQb9ikH1wc8V1jnRnW7NZjDQ&oe=6A355953",
              "video_url": "https://www.facebook.com/ads/library/?id=1070430385010391",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            }
          ]
        }
      ]
    }
  ]
};
