window.STRATEGY_DATA = {
  "campaign": "QV Summer Product Launch",
  "product": "QV (Ego Pharmaceuticals)",
  "run_id": "fbf9ee60-db97-45e5-b6ed-6f8af2b7edfe",
  "sources": [
    {
      "key": "ugc",
      "label": "UGC",
      "persona_count": 6,
      "generation_count": 45,
      "icps": [
        {
          "name": "A broad, intergenerational audience looking for versatile skin and wellness solutions that work regardless of age or life stage.",
          "persona": "A broad, intergenerational audience looking for versatile skin and wellness solutions that work regardless of age or life stage.",
          "pains": [
            "One-size-fits-all products that fail",
            "Complexity in routine",
            "Generic marketing",
            "Inconsistent results across different ages"
          ],
          "scrolls_for": [
            "Universal skincare hacks",
            "Family-friendly health tips",
            "Simple daily rituals",
            "Authentic product reviews",
            "Time-saving wellness routines"
          ],
          "quote": "I just want something effective that works for my whole life.",
          "tags": [
            "shorts",
            "makeup",
            "jellymakeupthing0",
            "relaxingvideos",
            "foryoupage",
            "acne",
            "acnepositivity",
            "paintings",
            "reveal",
            "cuidadodelapiel"
          ],
          "count": 8,
          "videos": [
            {
              "handle": "@jellymakeupthings0",
              "nickname": "jellymakeupthings0",
              "country": "United States",
              "metric": "523K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642315251261672726.jpg",
              "description": "ASMR Skincare Routine on Watermelon relaxing #shorts #makeup #jellymakeupthing0 #relaxingvideos #foryoupage❤️❤️ ",
              "hook": "Experience a unique ASMR skincare routine as a hand with googly eyes applies product to a watermelon, creating a strangely satisfying sensory experience.",
              "format": "asmr",
              "tier": "MEGA",
              "score": 367.49,
              "video_url": "https://www.tiktok.com/@jellymakeupthings0/video/7642315251261672726",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642315251261672726",
              "picked": true
            },
            {
              "handle": "@klarativ",
              "nickname": "klara🪿💫",
              "country": "Germany",
              "metric": "347K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642386909955706145.jpg",
              "description": "people who get it, get it. #acne #acnepositivity #paintings #reveal ",
              "hook": "A person holds up a paper with the word \"acne\" written on it, hinting at an upcoming reveal or artistic creation.",
              "format": "diy",
              "tier": "MEGA",
              "score": 211.47,
              "video_url": "https://www.tiktok.com/@klarativ/video/7642386909955706145",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642386909955706145",
              "picked": false
            },
            {
              "handle": "@axisymedicalshop",
              "nickname": "axisYmedicalshop",
              "country": "South Africa",
              "metric": "160K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7635316214084111637.jpg",
              "description": "🚨 LIMITED STOCK ALERT 🚨 💬 “I didn’t expect results this fast… my dark spots are fading already!” 💬 “Best decision I made for my skin this year.” This is NOT your regular skincare… ✨ The product everyone is switching to for clear, glowing skin ✨ 255+ sold in the past 7 days ✨ Only a few units left in stock 👉 Buy 2, Get 2 FREE 👉 FREE nationwide shipping 🇿🇦 #s#skincarek#koreanskincareg#glassskind#darkspotsa#acne#skincaretips#selfcare     ",
              "hook": "This creator raves about a \"Dark Spot Correcting Glow Serum,\" showcasing its fast-acting results for clear, glowing skin.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 113.76,
              "video_url": "https://www.tiktok.com/@axisymedicalshop/video/7635316214084111637",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7635316214084111637",
              "picked": false
            },
            {
              "handle": "@shimiramos2.0",
              "nickname": "shimiramos2.0",
              "country": "Philippines",
              "metric": "68K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643307202190806290.jpg",
              "description": "This is a reminder that.. its not permanent everything will go away just go through that phase and at the same time enjoy life even its an acne ☺️🥹 #acnejourney #acne #fyp #foryou ",
              "hook": "Tired of masking breakouts? This video captures the relatable struggle of covering acne and offers a message of hope and self-acceptance.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 59.68,
              "video_url": "https://www.tiktok.com/@shimiramos2.0/video/7643307202190806290",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643307202190806290",
              "picked": false
            },
            {
              "handle": "@hania.amir.2",
              "nickname": "Hania amir",
              "country": "Pakistan",
              "metric": "306K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7644178648379002134.jpg",
              "description": "#haniaamir #viral #vlogs #FYP #foryoupage❤️❤️ ",
              "hook": "A woman in pajamas and a towel-wrapped head holds a pink beauty tool, ready for her nighttime skincare routine in a yellow-accented kitchen.",
              "format": "vlog",
              "tier": "MODERATE",
              "score": 49.34,
              "video_url": "https://www.tiktok.com/@hania.amir.2/video/7644178648379002134",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7644178648379002134",
              "picked": false
            },
            {
              "handle": "@bonita.glow3",
              "nickname": "bonita.glow",
              "country": "United States",
              "metric": "154K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643771656292289806.jpg",
              "description": "ing to consistency is KEY look at that difference.Try HKH Plant Retinol Time capsule.🔥🫦🍟 ⚡️🧚🏻‍♀️🗽🦩#cuidadodelapiel#glowup#antiedad#antiarrugas#hkh ",
              "hook": "A man with dramatic eye makeup showcases the dramatic difference in skin texture after using a new product, highlighting anti-aging benefits.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 30.69,
              "video_url": "https://www.tiktok.com/@bonita.glow3/video/7643771656292289806",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643771656292289806",
              "picked": false
            },
            {
              "handle": "@sanwariya_cosmetics_hapur",
              "nickname": "SANWARIYA COSMETIC & JEWELLERY STORE || HAPUR",
              "country": "India",
              "metric": "27K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYGz3Zcsk8B.jpg",
              "description": "Variety of cleansers",
              "hook": "A shopkeeper showcases a vibrant display of cleansers and skincare products, highlighting a diverse range of brands and packaging.",
              "format": "other",
              "tier": "MODERATE",
              "score": 22.01,
              "video_url": "https://www.instagram.com/p/DYGz3Zcsk8B/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYGz3Zcsk8B/embed",
              "picked": false
            },
            {
              "handle": "@roydevita_md",
              "nickname": "Roy de Vita",
              "country": "Italy",
              "metric": "265K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7627394751020403989.jpg",
              "description": "LA FDA LO SA DAL 2019. TU NO.  La differenza tra SPF 30 e SPF 100 è due punti percentuali. Il prezzo? Anche il triplo. Nel 2019 la FDA ha analizzato 16 ingredienti delle creme solari. Solo 2 sono classificati sicuri ed efficaci. Per 12 i dati sono insufficienti. Nel 2020 uno studio su JAMA ha dimostrato che i filtri chimici più comuni entrano nel sangue dopo una sola applicazione. La protezione non è nel numero — è nel comportamento. Il numero sull’etichetta protegge il fatturato. Non la tua pelle. #cremesolare #spf  #melanoma  #chirurgiaplastica  #metodoveta",
              "hook": "The FDA knows the truth about sunscreen ingredients since 2019, but do you? Discover why SPF numbers can be misleading and what truly protects your skin.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 21.54,
              "video_url": "https://www.tiktok.com/@roydevita_md/video/7627394751020403989",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7627394751020403989",
              "picked": false
            }
          ]
        },
        {
          "name": "Socially active teenagers aged 13 to 19 who are navigating the physical and social changes of adolescence.",
          "persona": "Socially active teenagers aged 13 to 19 who are navigating the physical and social changes of adolescence.",
          "pains": [
            "cluttered skin and breakouts",
            "social anxiety from peer judgement",
            "desire for independence from parental choices"
          ],
          "scrolls_for": [
            "relatable school stories",
            "get ready with me routines",
            "trending dance challenges",
            "honest product reviews"
          ],
          "quote": "I just want my skin to look good for the weekend.",
          "tags": [
            "makeup",
            "acneproneskin",
            "makeuproutine",
            "rhode",
            "relatable"
          ],
          "count": 3,
          "videos": [
            {
              "handle": "@ocskinspa",
              "nickname": "OC Skin Spa",
              "country": "United States",
              "metric": "1.3M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYeOfENOV0L.jpg",
              "description": "Teen acne facial treatment🪄\n\n#ocskinspa #facial #acnetreatment #acneproneskin #acneskincare",
              "hook": "Watch this satisfying close-up of a professional facial treatment targeting teen acne, showing a close-up of the skin before and during the process.",
              "format": "tutorial",
              "tier": "MEGA",
              "score": 796.3,
              "video_url": "https://www.instagram.com/p/DYeOfENOV0L/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYeOfENOV0L/embed",
              "picked": true
            },
            {
              "handle": "@ashika__545",
              "nickname": "Ashika",
              "country": "Australia",
              "metric": "1.6M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYtaipqIqTS.jpg",
              "description": "My recent skincare update 💚✨\nTrying the Arencia ERASER SHOT GLYCOLIC ACID BOOSTER and documenting my experience 🫶\n@arencia_global \n#arencia #erasershot #acne #fyp #koreanskincare",
              "hook": "Watch this user document their journey to clear acne in 7 days using a targeted glycolic acid booster. See Day 1 results!",
              "format": "before after",
              "tier": "HIGH",
              "score": 111.02,
              "video_url": "https://www.instagram.com/p/DYtaipqIqTS/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYtaipqIqTS/embed",
              "picked": false
            },
            {
              "handle": "@emmakathleenee",
              "nickname": "emmakathleenee",
              "country": "United States",
              "metric": "28K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643202257055468830.jpg",
              "description": "the BEST products!! #makeup #acneproneskin #makeuproutine #rhode #relatable ",
              "hook": "A young woman with pink pajamas and makeup pouts while holding a Starbucks drink, sharing her go-to products for acne-prone skin.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 25.56,
              "video_url": "https://www.tiktok.com/@emmakathleenee/video/7643202257055468830",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643202257055468830",
              "picked": false
            }
          ]
        },
        {
          "name": "Active young adults in their 20s or early 30s focused on establishing a balanced lifestyle and preventative self-care.",
          "persona": "Active young adults in their 20s or early 30s focused on establishing a balanced lifestyle and preventative self-care.",
          "pains": [
            "cluttered morning routines",
            "budget constraints for premium products",
            "inconsistent sleep cycles",
            "social media comparison burnout"
          ],
          "scrolls_for": [
            "relatable daily vlogs",
            "quick healthy meal prep",
            "affordable skincare hauls",
            "productivity hacks"
          ],
          "quote": "I just want a routine that actually works without breaking the bank.",
          "tags": [
            "srm",
            "suaruamat",
            "colorkey",
            "skincare",
            "xuhuong"
          ],
          "count": 7,
          "videos": [
            {
              "handle": "@japan_cosmehub",
              "nickname": "japan_cosmehub",
              "country": "Japan",
              "metric": "481K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620765169139944735.jpg",
              "description": "Perfect whip difference👀‼️ #jbeauty #japanshopping #japanhaul #beautytok #japantravel ",
              "hook": "Struggling to choose between Japan's popular 'Perfect Whip' cleansers? This video breaks down the differences between the blue, pink, white, and green formulas to help you pick the best one for your skin type!",
              "format": "voiceover",
              "tier": "MEGA",
              "score": 480.72,
              "video_url": "https://www.tiktok.com/@japan_cosmehub/video/7620765169139944735",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620765169139944735",
              "picked": true
            },
            {
              "handle": "@ayamnicher",
              "nickname": "ayamnicher",
              "country": "France",
              "metric": "597K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620549421247237397.jpg",
              "description": "Fresh and clean with @Garnier  #garnierskin #serumcleanser #fastbright #vitaminec #ad",
              "hook": "Glow up your skin! See how this Garnier Vitamin C serum cleanser delivers a fresh and bright complexion.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 195.74,
              "video_url": "https://www.tiktok.com/@ayamnicher/video/7620549421247237397",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620549421247237397",
              "picked": false
            },
            {
              "handle": "@linh1001022",
              "nickname": "Mỹ Linhhhh",
              "country": "Vietnam",
              "metric": "257K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7626374637940772114.jpg",
              "description": "#srm #suaruamat #colorkey #skincare #xuhuong ",
              "hook": "A hand holds up a green Luminous Purifying Gel Cleanser with a matching green sponge, asking viewers if they're getting enough product.",
              "format": "product review",
              "tier": "HIGH",
              "score": 188.89,
              "video_url": "https://www.tiktok.com/@linh1001022/video/7626374637940772114",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7626374637940772114",
              "picked": false
            },
            {
              "handle": "@mina_biyou0",
              "nickname": "みなきメンズ美容",
              "country": "Japan",
              "metric": "699K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7631825940439633173.jpg",
              "description": "シカリ洗顔を2週間使ったレビュー載せます！ #シカリ #SHIKARI #洗顔 #正直レビュー #tiktokショップ ",
              "hook": "Is this the \"magic\" facial cleanser that delivers on its promises? See the unfiltered results after two weeks of use!",
              "format": "product review",
              "tier": "HIGH",
              "score": 137.16,
              "video_url": "https://www.tiktok.com/@mina_biyou0/video/7631825940439633173",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7631825940439633173",
              "picked": false
            },
            {
              "handle": "@flaviasantanav",
              "nickname": "Flávia Santana | UGC Creator",
              "country": "Brazil",
              "metric": "908K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DWTu0EEkR1d.jpg",
              "description": "Me explica como um produto consegue limpar, tratar e ainda deixar esse glow na pele? ✨\n\nO novo Serumnete chegou pra provar que dá sim pra ter uma pele radiante sem complicar a rotina. 💛\nCuida como um sérum e limpa como sabonete, tudo em um único passo!\n\nPerfeito pra quem não tem tempo ou até preguiça mesmo, mas não abre mão de uma pele bonita, uniforme e com aquele glow natural.\n\n@GarnierBrasil\n#LimpezaGarnier #SerumneteGarnier #publi",
              "hook": "This Garnier \"Serumnete\" promises to clean, treat, and add glow to your skin in one easy step, simplifying your routine for radiant results.",
              "format": "product review",
              "tier": "HIGH",
              "score": 78.29,
              "video_url": "https://www.instagram.com/p/DWTu0EEkR1d/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DWTu0EEkR1d/embed",
              "picked": false
            },
            {
              "handle": "@nandid_",
              "nickname": "nandid_",
              "country": "United States",
              "metric": "113K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7624273645296307476.jpg",
              "description": "If you’re dealing with whiteheads that keep coming back, slow this part down   #sacleanser #whiteheads #acneskincare #skincareproducts#cerave",
              "hook": "Struggling with persistent whiteheads? This video slows down to reveal the key to tackling them with CeraVe cleanser.",
              "format": "product review",
              "tier": "MODERATE",
              "score": 41.88,
              "video_url": "https://www.tiktok.com/@nandid_/video/7624273645296307476",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7624273645296307476",
              "picked": false
            },
            {
              "handle": "@tiiffaaww",
              "nickname": "tiffa",
              "country": "Indonesia",
              "metric": "23K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7617457162217966855.jpg",
              "description": "Skin barrier lagi rusak? Saatnya balik ke basic skincare ✨ Pakai CeraVe yang mengandung 3 essential ceramides + MVE Technology untuk bantu jaga kelembapan kulit lebih lama 🤍 Gentle tapi tetap efektif buat daily skincare #CeraVeID  #ClearYourSkinADerm ",
              "hook": "Get your skin barrier back on track with CeraVe's Blemish Control line, featuring essential ceramides for lasting hydration. Find it now at the Official CeraVe Store!",
              "format": "product review",
              "tier": "MODERATE",
              "score": 20.64,
              "video_url": "https://www.tiktok.com/@tiiffaaww/video/7617457162217966855",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7617457162217966855",
              "picked": false
            }
          ]
        },
        {
          "name": "Young adults in their late teens and early twenties navigating the transitions of early independence and social pressure.",
          "persona": "Young adults in their late teens and early twenties navigating the transitions of early independence and social pressure.",
          "pains": [
            "Feeling behind peers",
            "Financial instability",
            "Academic and career burnout",
            "Difficulty establishing healthy routines"
          ],
          "scrolls_for": [
            "Relatable lifestyle vlogs",
            "Budget-friendly life hacks",
            "Mental health advocacy",
            "Productivity and study tips"
          ],
          "quote": "I am just trying to figure out my life without burning out.",
          "tags": [
            "clip",
            "fyp",
            "sunscreen",
            "skincare",
            "glowup",
            "бьютиблог",
            "grwm",
            "косметика",
            "acne",
            "hormonalacne"
          ],
          "count": 12,
          "videos": [
            {
              "handle": "@sosmedsulsel",
              "nickname": "SOSMED SULSEL",
              "country": "Indonesia",
              "metric": "1.4M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643316137253424391.jpg",
              "description": "Balai Besar Pengawas Obat dan Makanan (BBPOM) Makassar menyita 7.092 picis skincare dari berbagai merek produk kosmetik ilegal dan mengandung merkuri di Kota Makassar, Sulawesi Selatan (Sulsel). Produk skincare atau kosmetik perawatan kulit ini dibuat di salah satu rumah yang diproduksi wanita berinisial S (28). \"Ditemukan aktivitas produksi kosmetik berupa sarana tidak memiliki izin produksi/sarana ilegal dan produk kosmetik ilegal mengandung bahan berbahaya, dengan rincian produk jadi sebanyak 8 item, 7.092 picis,\" ujar Kepala BBPOM Makassar Yosef Dwi Irwan Prakasa Setiawan saat konferensi pers di kantornya Jalan Baji Minasa, Kamis (21/5/2026). Produk kosmetik ilegal mengandung bahan b3rbah4y4, dengan rincian produk jadi sebanyak 8 item. Total yang disita 7.092 picis serta ditemukan bahan baku produk, produk rumahan, kemasan, label dan alat produksi sederhana. \"Produk yang disita terdiri dari Putri Glow Face Toner, Putri Glow Facial Wash, Putri Glow Day Cream, Putri Glow Night Cream, Putri Glow Serum C hingga Putri Glow Body Lotion,\" jelas Yosef. Yosef mengatakan, ribuan picis dari 6 produk tersebut diproduksi menggunakan bahan b3rbah4y4. Hasil pengujian laboratorium menunjukkan produk positif mengandung merkuri, hidrokuinon dan asam retinoat. \"Terhadap produk kosmetik ilegal ini telah pengujian di laboratorium BBPOM di Makassar dan hasilnya positif merkuri, hidrokinon dan asam retinoat,\" jelasnya. Di lokasi tersebut, petugas turut menemukan bahan baku kosmetik tanpa izin edar BPOM seperti DL Hydroquinone Tretinoin Babyface 3, La Bella Cream, Erna Whitening Cream, Super SP Special dan BL Cream. Selain itu ditemukan alat produksi sederhana berupa ember, mixer, corong, saringan hingga hot air gun. \"Jadi pelaku mencampur produk legal dan ilegal di kosmetik produksinya,\" ungkap Yosef. BBPOM Makassar mengungkap nilai ekonomi seluruh barang temuan diperkirakan mencapai Rp 700 juta. Produk tersebut dipasarkan secara online dan offline dalam bentuk paket skincare. \"Rata-rata produksi per pekan bisa mencapai 300 sampai dengan 500 paket, dengan harga jual per paketnya Rp 130 ribu maka estimasi omzet per pekan bisa mencapai Rp 39 juta sampai Rp 65 juta,\" ungkap Yosef. Diketahui, sejumlah produk kosmetik ilegal dan mengandung bahan b3rbah4y4 itu disita dari di sebuah rumah di Kelurahan Paropo, Kecamatan Panakkukang, Makassar, Selasa (19/5). Rumah tersebut dijadikan sebagai pabrik skincare. Adapun merek produk skincare ilegal dan b3rbah4y4 yang disita sebagai berikut: Putri Glow Face Toner Putri Glow Facial Wash Putri Glow Day Cream Putri Glow Night Cream Putri Glow Serum C Putri Glow Body Lotion Selengkapnya di : https://www.detik.com/sulsel/makassar/d-8498828/7-092-skincare-ilegal-disita-di-pabrik-rumahan-makassar-ini-daftar-mereknya",
              "hook": "Illegal skincare worth millions seized in Makassar! Authorities raid a home factory producing dangerous, mercury-laced cosmetics, including popular brands.",
              "format": "voiceover",
              "tier": "MEGA",
              "score": 410.68,
              "video_url": "https://www.tiktok.com/@sosmedsulsel/video/7643316137253424391",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643316137253424391",
              "picked": true
            },
            {
              "handle": "@_yuvicasarkar_",
              "nickname": "Yuvica 🎀",
              "country": "India",
              "metric": "310K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYPJEZwo6pw.jpg",
              "description": "My go-to routine from @dotandkey.skincare 💚",
              "hook": "A woman shares her favorite Dot & Key Cica Calming Oil-Free Moisturizer in a close-up skincare routine.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 137.31,
              "video_url": "https://www.instagram.com/p/DYPJEZwo6pw/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYPJEZwo6pw/embed",
              "picked": false
            },
            {
              "handle": "@epidermfxglasgow",
              "nickname": "EpidermFx",
              "country": "United Kingdom",
              "metric": "217K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7639477865146486039.jpg",
              "description": "What’s the best treatment for deep acne scars?  #acnescars #acnee #acnescarring #acnetok #skintok ",
              "hook": "Seeking the best treatment for deep acne scars? This video dives into a study comparing lasers, fillers, surgery, and more to reveal the top solutions.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 129.87,
              "video_url": "https://www.tiktok.com/@epidermfxglasgow/video/7639477865146486039",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7639477865146486039",
              "picked": false
            },
            {
              "handle": "@keiisand_",
              "nickname": "Kary",
              "country": "Mexico",
              "metric": "483K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7634724423446187271.jpg",
              "description": "Hermanas ✨✨ probé este truquito que vi por todo mi fyp y si me funcionó 🤩🤩🤩🤩 si redujo 1 -2 tonos y vaos por mas porque eato apenas empieza. Es el serum de vitamina c de @Arencia y lo Puedes conseguir en @YesStyle  Te dejo mi código de influencer para un descuento en tu Compra: KEIIMS07 #arencia #vitaminac #axilasmanchadas #aclararlapiel #vitamincboostershot ",
              "hook": "Watch this TikToker apply a bright yellow serum to her underarms, claiming it brightens them by 1-2 shades in just 7 days!",
              "format": "tutorial",
              "tier": "HIGH",
              "score": 118.22,
              "video_url": "https://www.tiktok.com/@keiisand_/video/7634724423446187271",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7634724423446187271",
              "picked": false
            },
            {
              "handle": "@blonbievvanili",
              "nickname": "Блонди в ванили🤍",
              "country": "Russia",
              "metric": "150K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642294197332004128.jpg",
              "description": "#skincare #glowup #бьютиблог #grwm #косметика ",
              "hook": "A dreamy pink-themed skincare collection is neatly organized in a rotating carousel organizer, showcasing popular beauty products for a glow-up.",
              "format": "product review",
              "tier": "HIGH",
              "score": 103.23,
              "video_url": "https://www.tiktok.com/@blonbievvanili/video/7642294197332004128",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642294197332004128",
              "picked": false
            },
            {
              "handle": "@tangy.clipz",
              "nickname": "tangy.clipz",
              "country": "United States",
              "metric": "193K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7626119285156400397.jpg",
              "description": "Paeka gets advice from Nina on sun damage skin and gets this sunscreen and is now glowing 😍#clip #fyp #sunscreen #skincare ",
              "hook": "Paeka shares her glowing skin secret after receiving sunscreen advice from Nina, transforming her sun-damaged complexion.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 95.35,
              "video_url": "https://www.tiktok.com/@tangy.clipz/video/7626119285156400397",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7626119285156400397",
              "picked": false
            },
            {
              "handle": "@accryzn",
              "nickname": "Ryzn",
              "country": "Indonesia",
              "metric": "136K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643279342906117394.jpg",
              "description": "ohhh ternyata yang basic doang udah cukup banget buat cowok wkwk #set1awanade #skincare #facewash #barberdaily ",
              "hook": "Gamers, get ready for the ultimate skincare routine! Learn the basic steps to keep your face fresh without the fuss.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 61.83,
              "video_url": "https://www.tiktok.com/@accryzn/video/7643279342906117394",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643279342906117394",
              "picked": false
            },
            {
              "handle": "@shimiramos2.0",
              "nickname": "shimiramos2.0",
              "country": "Philippines",
              "metric": "65K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642926285303418130.jpg",
              "description": "ACNE IS NORMAL!!!! ❤️🥰😁 #acne #hormonalacne #fyp #foryou ",
              "hook": "Dealing with acne? This creator shares a powerful message: \"f*ck what others think about acne\" and embraces life with confidence.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 56.87,
              "video_url": "https://www.tiktok.com/@shimiramos2.0/video/7642926285303418130",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642926285303418130",
              "picked": false
            },
            {
              "handle": "@joya.huwylr",
              "nickname": "Joy★",
              "country": "Netherlands",
              "metric": "642K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7626666328857890070.jpg",
              "description": "Werbung I Wenn du auch mineralischen und sofort wirksamen Sonnenschutz bevorzugst, empfehle ich dir das UV-Glow-Fluid von @Weleda  #weleda #weledaboosterdrops #sonnenschutz #schwizerdütsch #skincare ",
              "hook": "This creator shows how to apply a mineral sunscreen for instant sun protection, demonstrating the product's texture on their skin.",
              "format": "product review",
              "tier": "MODERATE",
              "score": 47.93,
              "video_url": "https://www.tiktok.com/@joya.huwylr/video/7626666328857890070",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7626666328857890070",
              "picked": false
            },
            {
              "handle": "@mycloud_d",
              "nickname": "mycloud_d",
              "country": "Vietnam",
              "metric": "53K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7638143455935417608.jpg",
              "description": "Được cả đôiii #teeteepor #twnpich #porsuppakarn ",
              "hook": "Two handsome young men share a sunscreen tube, one holding it up as a playful prop.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 42.9,
              "video_url": "https://www.tiktok.com/@mycloud_d/video/7638143455935417608",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7638143455935417608",
              "picked": false
            },
            {
              "handle": "@yagya_chopra",
              "nickname": "Yagya Chopra 🤍Product Reviewer + Lifestyle Creator",
              "country": "India",
              "metric": "137K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DXbcuY1Eu1W.jpg",
              "description": "Oily skin struggles are real, but this one actually balances it out. No grease, just soft, fresh, healthy-looking skin 🤍 Foxtale Moisturiser is loveeeeeee\n\n#Foxtale #Foxtaleskin",
              "hook": "Struggling with oily skin? Watch how this moisturizer transforms greasy skin into a soft, fresh, and healthy glow without any residue.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 29.34,
              "video_url": "https://www.instagram.com/p/DXbcuY1Eu1W/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DXbcuY1Eu1W/embed",
              "picked": false
            },
            {
              "handle": "@helenynasta",
              "nickname": "Helen",
              "country": "Australia",
              "metric": "32K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7637256389491985672.jpg",
              "description": "Testing the brand new @chanel.beauty Les Beiges Correcteur de Teint (Serum Concealer). As someone who prioritizes clinical luxury and skin revision, I’m always looking for formulas that bridge the gap between treatment and pigment. This is a true serum-concealer hybrid. It’s designed to provide that editorial, ‘second-skin’ finish that looks like you’ve just had a professional facial. Perfect for that Madelyn Cline inspired aesthetic where the skin is the hero, not the makeup.   #ChanelBeauty #LesBeiges #SerumConcealer #ClinicalLuxury #SkinFirst ",
              "hook": "Get a flawless, 'second-skin' look with the new Chanel Les Beiges Serum Concealer, designed for a hydrated, radiant finish.",
              "format": "product review",
              "tier": "MODERATE",
              "score": 26.6,
              "video_url": "https://www.tiktok.com/@helenynasta/video/7637256389491985672",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7637256389491985672",
              "picked": false
            }
          ]
        },
        {
          "name": "Women in their 20s to 50s seeking to enhance their daily wellness and self-care routines through accessible health and beauty solutions.",
          "persona": "Women in their 20s to 50s seeking to enhance their daily wellness and self-care routines through accessible health and beauty solutions.",
          "pains": [
            "lack of consistent energy",
            "visible signs of aging",
            "complex multi-step routines",
            "difficulty finding effective products"
          ],
          "scrolls_for": [
            "morning routine ideas",
            "honest product reviews",
            "glowing skin transformations",
            "quick healthy recipes"
          ],
          "quote": "I just want a simple routine that actually makes me feel good.",
          "tags": [
            "skincareover40",
            "over40mom",
            "tretinoin",
            "amlactin",
            "suncapcream",
            "beautytips",
            "skincareroutine",
            "skincareviral",
            "moisturizers",
            "brazilianwaxaftercare"
          ],
          "count": 12,
          "videos": [
            {
              "handle": "@fafiallel",
              "nickname": "farah",
              "country": "Somalia",
              "metric": "1.5M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7641865713195486472.jpg",
              "description": "Micro abrasion plus kojic acid scrub  followed with gentle brightening cream and sealed with brightening oil 👌🏾 will be sharing more stay tuned 🫶🏾 #bodyhyperpigmentation #acnescartreatment #skincaretips #somalitiktok #fypシ゚ ",
              "hook": "Witness the 3 1/2 week transformation of skin with a \"trio\" of brightening and scar treatments, promising clearer skin ahead.",
              "format": "before after",
              "tier": "MEGA",
              "score": 297.62,
              "video_url": "https://www.tiktok.com/@fafiallel/video/7641865713195486472",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7641865713195486472",
              "picked": true
            },
            {
              "handle": "@dra.beatrizkalil",
              "nickname": "dra.beatrizkalil",
              "country": "Brazil",
              "metric": "1.2M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642352081088711957.jpg",
              "description": "Use o meu cupom de desconto no site oficial Skinceuticals:  10% de desconto + Frete Grátis!  #bl_d8a9 #botox #kbeauty #ptiox #skinceuticalsSkinCare     @SkinCeuticals ",
              "hook": "See how this SkinCeuticals P-Tiox serum promises to improve wrinkle appearance, skin texture, and radiance with just a few drops.",
              "format": "product review",
              "tier": "MEGA",
              "score": 277.65,
              "video_url": "https://www.tiktok.com/@dra.beatrizkalil/video/7642352081088711957",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642352081088711957",
              "picked": false
            },
            {
              "handle": "@brynn.the.waxer",
              "nickname": "Brynn | Boise Waxer",
              "country": "United States",
              "metric": "199K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7620982056402685198.jpg",
              "description": "My opinion on moisturizers for Brazilian wax aftercare. Please moisturize! It will make your wax cleaner and less painful! #moisturizers #brazilianwaxaftercare #waxingaftercare #waxspecialist #greenscreen ",
              "hook": "Stop waxing pain and ingrown hairs! This expert reveals the best and worst moisturizers for post-Brazilian wax aftercare.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 91.3,
              "video_url": "https://www.tiktok.com/@brynn.the.waxer/video/7620982056402685198",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7620982056402685198",
              "picked": false
            },
            {
              "handle": "@g.sydoruk",
              "nickname": "g.sydoruk",
              "country": "Ukraine",
              "metric": "1M",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DYMsl8vq9Xa.jpg",
              "description": "💗🫧 #asmrroutine",
              "hook": "Achieve ultimate glow with this ASMR skincare routine, featuring a satisfying\"Glow Up\" moisturizer application. Pure pampering sounds and visuals!",
              "format": "voiceover",
              "tier": "HIGH",
              "score": 72.14,
              "video_url": "https://www.instagram.com/p/DYMsl8vq9Xa/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DYMsl8vq9Xa/embed",
              "picked": false
            },
            {
              "handle": "@wellness.weichen",
              "nickname": "Dr Wei Chen",
              "country": "United States",
              "metric": "71K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7639410379730259220.jpg",
              "description": "It starts so quietly after 40! The longer you wait the further back your Day 1 becomes.  Link in Bio 🔗  #hairgrowth #hairloss #hairlinerestoration #usahealth #hairlossfix ",
              "hook": "POV: Applying hair growth serum on thinning hair, with text stating 'Day 1' and a broken heart emoji, signaling a journey to fix hair loss.",
              "format": "tutorial",
              "tier": "HIGH",
              "score": 51.01,
              "video_url": "https://www.tiktok.com/@wellness.weichen/video/7639410379730259220",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7639410379730259220",
              "picked": false
            },
            {
              "handle": "@doc_rapunzel",
              "nickname": "Doc.Rapunzel",
              "country": "India",
              "metric": "51K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7627448603069402375.jpg",
              "description": "Resonable sunblock✅🥰#suncapcream #beautytips #skincareroutine #beautytips #skincareviral ",
              "hook": "Protect your skin with \"Reasonable Sunblock\" from Suncap Cream, featuring SPF 60 and Vitamin E for just 600!",
              "format": "product review",
              "tier": "MODERATE",
              "score": 49.37,
              "video_url": "https://www.tiktok.com/@doc_rapunzel/video/7627448603069402375",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7627448603069402375",
              "picked": false
            },
            {
              "handle": "@wellness.weichen",
              "nickname": "Dr Wei Chen",
              "country": "United States",
              "metric": "56K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7640519024018754837.jpg",
              "description": "Hair loss doesn’t just take your hair. It takes the version of yourself you thought you knew. I am not alone in this. And neither are you. Link in bio to what I recommend to my patients 🔗 #over50 #hairtok #hairgrowth #hairloss #hairgrowthtips ",
              "hook": "A doctor applies a golden serum to her scalp, sharing a vulnerable POV: 'He said he wasn't attracted to me anymore.'",
              "format": "tutorial",
              "tier": "MODERATE",
              "score": 40.49,
              "video_url": "https://www.tiktok.com/@wellness.weichen/video/7640519024018754837",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7640519024018754837",
              "picked": false
            },
            {
              "handle": "@flickacosmetics",
              "nickname": "Flicka Cosmetics",
              "country": "United States",
              "metric": "155K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7637778340627172630.jpg",
              "description": "order now and get original flicka ",
              "hook": "Get that perfect base with FLICKA Professional's Silk Touch Milk-Cream Moisturizer & Primer, promising a flawless makeup application.",
              "format": "tutorial",
              "tier": "MODERATE",
              "score": 38.99,
              "video_url": "https://www.tiktok.com/@flickacosmetics/video/7637778340627172630",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7637778340627172630",
              "picked": false
            },
            {
              "handle": "@by_sahouu",
              "nickname": "Siham سهـــام🎀",
              "country": "Algeria",
              "metric": "890K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/p/DXXEvm5jCMk.jpg",
              "description": "هاد ecran total لازم يكون عند كل بنت 💅🏻🥹 \n\n#fyp #vibes #follow #skincare #summer",
              "hook": "This video gives a rave review for a sunscreen essential for every girl, featuring the product and giving it a near-perfect score!",
              "format": "product review",
              "tier": "MODERATE",
              "score": 37.19,
              "video_url": "https://www.instagram.com/p/DXXEvm5jCMk/",
              "direct_video": "",
              "platform": "instagram",
              "embed_url": "https://www.instagram.com/p/DXXEvm5jCMk/embed",
              "picked": false
            },
            {
              "handle": "@alishael08",
              "nickname": "🦩Alisha881881🦩",
              "country": "United States",
              "metric": "41K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7627257213932850446.jpg",
              "description": "Replying to @Sonia Montoya8343 #skincareover40 #over40mom #tretinoin #amlactin ",
              "hook": "Watch this woman reveal her secret skincare routine, featuring Tretinoin and Amlactin for radiant skin over 40.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 34.0,
              "video_url": "https://www.tiktok.com/@alishael08/video/7627257213932850446",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7627257213932850446",
              "picked": false
            },
            {
              "handle": "@bonita.glow3",
              "nickname": "bonita.glow",
              "country": "United States",
              "metric": "151K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7643021152381586702.jpg",
              "description": "ing to consistency is KEY look at that difference.Try HKH Plant Retinol Time capsule.🔥🫦🍟 ⚡️🧚🏻‍♀️🗽🦩#cuidadodelapiel#glowup#antiedad#antiarrugas#hkh ",
              "hook": "Watch the dramatic transformation as skincare creates a visible difference, proving consistency is key for anti-aging results.",
              "format": "before after",
              "tier": "MODERATE",
              "score": 30.25,
              "video_url": "https://www.tiktok.com/@bonita.glow3/video/7643021152381586702",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7643021152381586702",
              "picked": false
            },
            {
              "handle": "@cutiepatooties609",
              "nickname": "cutiepatooties",
              "country": "South Korea",
              "metric": "240K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7642608255612603661.jpg",
              "description": "LISTEN TO THIS 🤯 #skincare #collagen #medicube #collagenjelly #faceroutine ",
              "hook": "This 61-year-old woman reveals her secret to reversing aging with a collagen jelly, leaving younger women asking for her routine.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 26.67,
              "video_url": "https://www.tiktok.com/@cutiepatooties609/video/7642608255612603661",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7642608255612603661",
              "picked": false
            }
          ]
        },
        {
          "name": "Adult women seeking reliable solutions for everyday health, beauty, or lifestyle management.",
          "persona": "Adult women seeking reliable solutions for everyday health, beauty, or lifestyle management.",
          "pains": [
            "Ineffective generic products",
            "Visible signs of aging",
            "Lack of self-care time",
            "Hormonal health fluctuations"
          ],
          "scrolls_for": [
            "Skincare routines",
            "Authentic product reviews",
            "Quick healthy recipes",
            "Stress management tips"
          ],
          "quote": "I just want a routine that actually works for my busy life.",
          "tags": [],
          "count": 3,
          "videos": [
            {
              "handle": "@axisymedicalshop",
              "nickname": "axisYmedicalshop",
              "country": "South Africa",
              "metric": "75K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7634005820098792724.jpg",
              "description": "🚨 ALMOST SOLD OUT — Reviews don’t lie ‘This changed my skin completely.’ ‘I get compliments EVERY day now.’ Why are so many people buying this right now? Because it actually works. 🎁 Buy 2 Get 1 FREE 🚚 FREE Delivery Nationwide ⏳ Offer ends in HOURS — next restock = higher price Don’t watch… be part of it.”",
              "hook": "See why this dark spot correcting serum is flying off the shelves with reviews like 'changed my skin completely' and 'compliments every day'.",
              "format": "talking head",
              "tier": "HIGH",
              "score": 53.26,
              "video_url": "https://www.tiktok.com/@axisymedicalshop/video/7634005820098792724",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7634005820098792724",
              "picked": true
            },
            {
              "handle": "@anamacedo.blz",
              "nickname": "Ana Macêdo | Beleza & Saúde",
              "country": "Brazil",
              "metric": "62K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7636161028715334930.jpg",
              "description": "E lá se foram 77 dias usando o GHK-Cu (cobre)... E como estou??? Só felicidades!!  🥳🥳🥳 #peptideodabeleza #peptideosdecolageno #fypシ゚ #fyp #viral ",
              "hook": "See the incredible skin transformation after 77 days of using GHK-Cu peptide serum! She shares her happy results, proving beauty comes from within.",
              "format": "talking head",
              "tier": "MODERATE",
              "score": 28.06,
              "video_url": "https://www.tiktok.com/@anamacedo.blz/video/7636161028715334930",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7636161028715334930",
              "picked": false
            },
            {
              "handle": "@lumiskin.app",
              "nickname": "Lumi",
              "country": "South Korea",
              "metric": "205K",
              "unit": "views",
              "cover": "https://images.0xw.app/viral_covers/7619319450923552021.jpg",
              "description": "fyi: my skin is combination, acne-prone and sensitive. Mentioned products in order: ▫️ medicube - Collagen Jelly Cream ▫️ Dr.G - R.E.D Blemish, Clear Soothing Cream ▫️ Round Lab - 1025 Dokdo Cream ▫️ medicube - Deep Vita C Capsule Cream ▫️ PURITO - Oat-In Calming Gel Cream ▫️ ETUDE - Soonjung 2x Barrier Intensive Cream ▫️ Dr. Althea - Aqua Marine Watery Cream ▫️ Dr. Althea - 345 Relief Cream #skincare #skincareproducts #kbeauty #koreanskincare #acnetreatment ",
              "hook": "See which Korean moisturizers get a \"yes\" or \"no\" for different skin types, including acne-prone and sensitive.",
              "format": "product review",
              "tier": "MODERATE",
              "score": 21.29,
              "video_url": "https://www.tiktok.com/@lumiskin.app/video/7619319450923552021",
              "direct_video": "",
              "platform": "tiktok",
              "embed_url": "https://www.tiktok.com/embed/v2/7619319450923552021",
              "picked": false
            }
          ]
        }
      ]
    },
    {
      "key": "paid_ad",
      "label": "Paid Ads",
      "persona_count": 2,
      "generation_count": 15,
      "icps": [
        {
          "name": "Conscious and self-conscious skincare enthusiasts aged 18-35, primarily women, dealing with persistent acne and oily skin.",
          "persona": "Conscious and self-conscious skincare enthusiasts aged 18-35, primarily women, dealing with persistent acne and oily skin.",
          "pains": [
            "persistent breakouts and oily sheen",
            "lack of specialized treatment options",
            "social anxiety due to skin clarity",
            "ineffective over-the-counter products"
          ],
          "scrolls_for": [
            "acne transformation stories",
            "ingredient deep dives for oily skin",
            "dermatologist-backed skincare routines",
            "honest product reviews"
          ],
          "quote": "I just want a specialized solution that actually clears my stubborn acne.",
          "tags": [
            "k-beauty inspired skincare",
            "clean beauty",
            "dermatology brand",
            "k-beauty inspired",
            "acne treatment",
            "skincare influencers",
            "dermatologist recommended style"
          ],
          "count": 3,
          "videos": [
            {
              "handle": "@Dr Niranjan Samani",
              "nickname": "The Derma Co.",
              "country": "india",
              "metric": "821K",
              "unit": "page likes",
              "cover": "https://scontent-lga3-2.xx.fbcdn.net/v/t39.35426-6/602938194_1193324382313226_8012454401082140043_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=UwZUWkxp8twQ7kNvwFOLZy6&_nc_oc=AdrlfFz7sS6iyaki78PUiWcK7R9j-T-Z2srUuy6miMcXO3bPOkmqgUGgQM_fUWI_Z68&_nc_zt=14&_nc_ht=scontent-lga3-2.xx&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&oh=00_Af81R_z5pogQWF5KShGmVPdk8UO-ClEVDdIHZ404yC4Jzw&oe=6A369437",
              "description": "Pimples ko kabhi phodo mat🙏\nAur agar already phoda heyna tho uska ek solution hey @thedermacoindia ka 10% niacinamide serum which will clear your acne marks, blemishes and Dark spots.\nConsistentpy isko try karo\n\nAcne marks solution\nPimples all gone thanks to this\n\nDisclaimer: I am sharing my personal experience and knowledge. Content provided on this instagram handle is for informational purposes only. This video is not intended to provide diagnosis, treatment or medical advice. Information on this instagram handle should not be considered as a substitute for advice from a qualified dermatologist. Please consult with a physician or Dermatologist regarding any medical or health-related diagnosis or treatment options\n\n#explore #explorepage #drniranjansamani #instagood #reels #reelitfeelit #skincare #instamood",
              "hook": "A man in a lab coat identifies common skin issues like acne marks and scars before promising a 7-day solution.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 821178,
              "direct_video": "https://video-lga3-1.xx.fbcdn.net/o1/v/t2/f2/m86/AQPkVUvEyx4PlIVceZTSEVg5XWGJr-i53bzk02j7pdWEuwoqeenpZYNTM1XX8u8gAfNHv-sjnBfNuf-gL5zVWYKW7rib7FOPybehcy8.mp4?_nc_cat=109&_nc_sid=b66105&_nc_ht=video-lga3-1.xx.fbcdn.net&_nc_ohc=BcvhuUddWG8Q7kNvwGf0xtt&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTMyODcyMTE2NTU2NzA4OSwiYXNzZXRfYWdlX2RheXMiOjIzMywidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjM5LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=8573fd75449544ea&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC84RDQyMzBFRkUzQ0EzMkUwMzdFNkVCRUY0N0M2RkY4OV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC83OTI2Njk3NzM3NDYxMzFfMzIyODU4NzQ5MDI1Mzk1MTE4Ni5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAm4pGikeCd3AQVAigCQzMsF0BD6p--dsi0GBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAZeadAQA&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&_nc_zt=28&oh=00_Af8_95ipcxLMlTaFGkBN6wqnD-D7FPb3biUGdATV0-Sk9w&oe=6A329106",
              "video_url": "https://www.facebook.com/ads/library/?id=25532941109720321",
              "platform": "paid",
              "embed_url": "",
              "picked": true
            },
            {
              "handle": "@Dot & Key",
              "nickname": "Dot & Key",
              "country": "india",
              "metric": "80K",
              "unit": "page likes",
              "cover": "https://scontent.fmem1-2.fna.fbcdn.net/v/t39.35426-6/617349578_735389109634815_2787741545230542278_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=0i8dxV6dB8AQ7kNvwGZFhE8&_nc_oc=Adohrg8yRkUYER2iOI9MiKYJNPToALI_z3H2x-yRb410unoE1_BVAwjIoe2LRz1Sl6Y&_nc_zt=14&_nc_ht=scontent.fmem1-2.fna&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&oh=00_Af8F1HyHqxYW6oCVb8J4HPDmWamZMLx961azRchNnrYakw&oe=6A3693FA",
              "description": "Oily, acne, annoyed? Super Cica Crew to the rescue!\nMeet the oily skin routine cleanser, serum & moisturizer 🍀\n\n✨ Cica (Centella) + Salicylic Facewash: Deeply cleanse excess oil\n✨ Cica (Centella) Niacinamide Serum: Treats acne & dark spots\n✨ Cica (Centella) + Niacinamide Oil-Free Moisturizer: Hydrates & soothes minus the oil\n\nSay hello to calm, clear & oil-free skin! 🌿\n\nWhy Dot & Key?\n✅ Dermatologically Tested\n✅ Cruelty-Free\n✅ No Nasties\n✅ Efficacy Uncompromised",
              "hook": "A close-up of a woman pointing to her face with the text overlay 'Acne Prone Skin?' to address a common skin concern.",
              "format": "demo",
              "tier": "AD",
              "score": 79900,
              "direct_video": "https://video.fmem1-2.fna.fbcdn.net/o1/v/t2/f2/m366/AQOXU8kS62FxLHbKmppogTdagZJ6v54GemDWu5n5Kz-L3NX4y59K7a8RClou0mzKbrbktRTvUueOsgTmCxQDGXwVsly3tHmS2yEqq3zSZN9mzw.mp4?_nc_cat=1&_nc_oc=AdpHlMqbqkIP_IZEYtc2cYiUsdVhfP5tnRPSpBPsoprEjynQkiAU-wPrEtCEexdw1s0&_nc_sid=b66105&_nc_ht=video.fmem1-2.fna.fbcdn.net&_nc_ohc=lEEy1rI6IGAQ7kNvwGDRS6G&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjg2OTE2MDUzNjAwMjMzMSwiYXNzZXRfYWdlX2RheXMiOjE0NCwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjIyLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=5c247a1038e8a7a5&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9DOTQ4NzZDOThEODZGRDU1QzlDQkZFQjdERDM3RjNCOV9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzExNDQwMjZEQzkyRTIxMjgxQzVFMjcyM0MzRkNGMjkyX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACa2vILQ5p-LAxUCKAJDMywXQDafO2RaHKwYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&_nc_zt=28&oh=00_Af9WRoRFd1s9NMAnxcrB_LXQaYl4Xv12MaFbEUc0kpZ7DA&oe=6A368441",
              "video_url": "https://www.facebook.com/ads/library/?id=1974104203451862",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Dot & Key",
              "nickname": "Dot & Key",
              "country": "india",
              "metric": "80K",
              "unit": "page likes",
              "cover": "https://scontent.fmem1-2.fna.fbcdn.net/v/t39.35426-6/656126886_1497253871860250_921030432799189319_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=vY-RVgp1vZ4Q7kNvwE5KpCf&_nc_oc=AdqGm2XSRqnjUi2pg4ROrcFenV96Ac7-x-EFdroTWzY_3qPJk88GdXDYOekCZLB4DrE&_nc_zt=14&_nc_ht=scontent.fmem1-2.fna&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&oh=00_Af8QNGuCzhktsFhl-aU3tfd73OAKWgYDQWz8oTKyOw5c1w&oe=6A36AC2E",
              "description": "Oily, acne, annoyed? Super Cica Crew to the rescue!\nMeet the oily skin routine cleanser, serum & moisturizer 🍀\n\n✨ Cica (Centella) + Salicylic Facewash: Deeply cleanse excess oil\n✨ Cica (Centella) Niacinamide Serum: Treats acne & dark spots\n✨ Cica (Centella) + Niacinamide Oil-Free Moisturizer: Hydrates & soothes minus the oil\n\nSay hello to calm, clear & oil-free skin! 🌿\n\nWhy Dot & Key?\n✅ Dermatologically Tested\n✅ Cruelty-Free\n✅ No Nasties\n✅ Efficacy Uncompromised",
              "hook": "A close-up of a woman showing her acne-prone skin while holding a green skincare tube.",
              "format": "demo",
              "tier": "AD",
              "score": 79900,
              "direct_video": "https://video.fmem1-2.fna.fbcdn.net/o1/v/t2/f2/m366/AQPG8cJjfSn4XH2p728CxLABcsAfnq-oLzfeqvq5jtsYCzv-XfFe1QViu95pyMo04342aHZBuj2_kLA3Qjiq2ZVfmdjwcFAvBRLr7f2eu5FgRg.mp4?_nc_cat=104&_nc_oc=AdqDGDDfn47G4EJb-DrFafs56PWPX47eZQ5RKY3Py5HRzXy1ZkVcfn4Sf7Ns32pZWoQ&_nc_sid=b66105&_nc_ht=video.fmem1-2.fna.fbcdn.net&_nc_ohc=_aD1tD5MWN4Q7kNvwHlRMZ6&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjE0Njk2NzczNTEyMjM1NDQsImFzc2V0X2FnZV9kYXlzIjo4NCwidmlfdXNlY2FzZV9pZCI6MTA3OTksImR1cmF0aW9uX3MiOjI0LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=124fa0a4f30294e1&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC82NDQ4RjZGRkVBQzI4NkMyMUYwMDU3NTgwNDMwMkI4RV9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzdGNDQ1NENGNzk2MUEzNkQ0MTZDQTg1M0QxQzUwQTk3X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbwg6LHvaqcBRUCKAJDMywXQDjKfvnbItEYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&_nc_zt=28&oh=00_Af9JYC_DFeT4VFQOr3p72BDoPOOEsvbZwoatoTt3fHAblg&oe=6A36A790",
              "video_url": "https://www.facebook.com/ads/library/?id=2094767934647947",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            }
          ]
        },
        {
          "name": "Budget-conscious female skincare enthusiasts aged 18-35 who prioritize efficient routines and a glowing, brightened complexion.",
          "persona": "Budget-conscious female skincare enthusiasts aged 18-35 who prioritize efficient routines and a glowing, brightened complexion.",
          "pains": [
            "Dull and uneven skin tone",
            "Overly complex and time-consuming routines",
            "High price tags on effective products",
            "Lack of visible radiance"
          ],
          "scrolls_for": [
            "Affordable skincare hauls",
            "Morning routine time-savers",
            "Glass skin tutorials",
            "Active ingredient explainers",
            "Before and after brightening results"
          ],
          "quote": "I want that glowy look without spending a fortune or an hour.",
          "tags": [
            "skincare",
            "wellness",
            "collagen",
            "skincare influencer",
            "k-beauty trends",
            "natural beauty",
            "skincare essentials",
            "indian beauty",
            "beauty influencers",
            "clean beauty"
          ],
          "count": 12,
          "videos": [
            {
              "handle": "@Kriti Sanon",
              "nickname": "Lets Hyphen",
              "country": "india",
              "metric": "14M",
              "unit": "page likes",
              "cover": "https://scontent-lga3-2.xx.fbcdn.net/v/t39.35426-6/542605461_1811160163127822_4566237441667751140_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=_9GZkWl46vYQ7kNvwHk5y7v&_nc_oc=AdozIalkzchNtJnk9I5uuEEW1AzOuuSNQrF2YrXfpphOv-R3tPJlNHpph2FtukkYiXQ&_nc_zt=14&_nc_ht=scontent-lga3-2.xx&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&oh=00_Af8d_TIW3vyYo8XsY1-gmEsnh7QKyh2J5Y5CU6vn7z061Q&oe=6A36BBAD",
              "description": "All I Need Sunscreen SPF 50 PA++++🫶🏻✨\nEver since i started my skincare journey, I never ever compromised on SPF. And for HYPHEN, we had to create something that hyphens moisturization with sun protection and goes even further, targeting sunspots and blue light damage.\nToo much to ask for? Well, say HELLO to the All I Need Sunscreen SPF 50 PA++++ - your ultimate sun-shield that protects from UV damage as well as blue light. 🌞\nIt is very lightweight, fragrance-free and leaves no white cast. All I Need Sunscreen truly lives up to its name - it's all YOU need in a sunscreen. Hyphen it into your routine now at letshyphen.com!\n\nIn this sunscreen we have HYPHENED 7 super-powerful ingredients like:\n\n➖ Kakadu Plum: Brightens your skin\n\n➖ Niacinamide: Reduces Pigmentation\n\n➖ Kojic Acid: Reduces sun-spots\n\n➖ Ceramides: Rebuild & strengthen skin’s barrier\n\n➖ Hyaluronic Acid: Deeply hydrates\n\n➖ Vitamin E: Protects from UV damage\n\n➖ Aloe Vera Extract: Prevents water loss from skin\n\nHead to letshyphen.com to HYPHEN us into your daily life!\n\n#Hyphen #LetsHyphen #HaveItAll #HyphenItAll #NewBeginnings #Skincare #AllINeedSunscreen #Sunscreen #SunShield #Hydration #SkincareEssentials #NewLaunch #CleanBeauty #VeganSkincare #PetaCertified #SustainableBeauty",
              "hook": "A close-up shot of the actress introducing the creation process of her brand's new sunscreen.",
              "format": "talking head",
              "tier": "AD",
              "score": 14000721,
              "direct_video": "https://video-lga3-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQNj_F3aQgJdBsJ8vE-OA5iM-CPLxiLFLwds5m1rNiCmlMB1dnNXbDok4gm0d08QrxCFdGXk_b8Vc8h8VwNo9zyh-8n2CeKpyAUuAzJooEyaVA.mp4?_nc_cat=111&_nc_sid=b66105&_nc_ht=video-lga3-1.xx.fbcdn.net&_nc_ohc=VHd2h_AaqswQ7kNvwEq5R_D&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjcwNjYyNDY5ODAxMzk5NDgsImFzc2V0X2FnZV9kYXlzIjo4MzMsInZpX3VzZWNhc2VfaWQiOjEwMTAxLCJkdXJhdGlvbl9zIjo1MiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=e28a5aa12009da39&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9CMjRDODVCRUI3RDU2RUZGMkE3N0E3Mjk2MzY0M0VCQl9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dIRGNzUm1HSXo4TEx6MEJBTFN3ejhySHlOb3ZidjRHQUFBRhUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbY7qvS2q2NGRUCKAJDMywXQEomZmZmZmYYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZeqdAQA&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&_nc_zt=28&oh=00_Af8QlY_yTzRJACy-MFrG0L64AKOM2geRQHbeZH3UDE-1TQ&oe=6A36A651",
              "video_url": "https://www.facebook.com/ads/library/?id=785414371102053",
              "platform": "paid",
              "embed_url": "",
              "picked": true
            },
            {
              "handle": "@Nykaa",
              "nickname": "Nykaa",
              "country": "india",
              "metric": "3.4M",
              "unit": "page likes",
              "cover": "https://scontent.fmem1-1.fna.fbcdn.net/v/t39.35426-6/546916836_642697201869492_7992179752784304751_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=wJjjkTXFxdkQ7kNvwF9wlWy&_nc_oc=AdrnSn0GrS839ue9D5Du4OIf_JwcmGWBFKAV7UowH1ayr0AeUojf-_RBTOJy8lRbaco&_nc_zt=14&_nc_ht=scontent.fmem1-1.fna&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&oh=00_Af-TjK9sPVl_h5yww1yuurt_QuAo9SZOotQFEwiPY0l2-g&oe=6A36B6F3",
              "description": "Fresh drops, endless beauty ✨Upgrade your beauty game with the hottest launches TODAY! Shop Now at Nykaa 🛍️",
              "hook": "The video opens with a woman claiming a new product on Nykaa has broken her long-standing loyalty to her previous routine.",
              "format": "tutorial",
              "tier": "AD",
              "score": 3449957,
              "direct_video": "https://video.fmem1-2.fna.fbcdn.net/o1/v/t2/f2/m366/AQPaOvtU-CWaLDQfhJzKYsf9QFB3fLqN1WLilUm0nrSXKCCVB1xDLaIkFjGn1o11tnojIf2ooFKbXrMrtN3Cb016YNmLsFqrHUYpwJzkEcObmA.mp4?_nc_cat=107&_nc_oc=AdqMnxdFlMCRW3Z7p_PUmGMI6mOZ84ngxUeLQTSCrVSZHPKq-tINiEYmPjzyUU57Kjc&_nc_sid=b66105&_nc_ht=video.fmem1-2.fna.fbcdn.net&_nc_ohc=eLFu83Xrkb0Q7kNvwFfxmn4&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjQyMzYwMDY1OTY2Njk3NDEsImFzc2V0X2FnZV9kYXlzIjoyNzgsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjo3OSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=cbe07c9131728ffc&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9FMjRCNzY3QzZENjVCQThGRTI4Mzk1QTQ2QUY1RTk4RV9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzM4NEEzOTkxOTlBNEM1M0I5QTZEQkUyQTI0OTNDNEJBX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbaxK_HhKiGDxUCKAJDMywXQFPmZmZmZmYYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=DarcqNq0tjjRvZfabqdaDA&_nc_ss=72289&_nc_zt=28&oh=00_Af8cgHKfbXsmn8FfFjnLTKKu_pGGWdDWpy6a9_nkqnkuLA&oe=6A369059",
              "video_url": "https://www.facebook.com/ads/library/?id=1568542287848380",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Aakriti Sharma",
              "nickname": "Mamaearth",
              "country": "india",
              "metric": "552K",
              "unit": "page likes",
              "cover": "https://scontent-atl3-1.xx.fbcdn.net/v/t39.35426-6/650343983_780097934745447_9053995988565627338_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=u6Jm56ll0LIQ7kNvwFWMseZ&_nc_oc=Ado3DwdwkzFArFW7lS53wkgnLjzAfmfxM-K4FaLlt_Xtje5FDZK6iGdyMpZa7BWqBDg&_nc_zt=14&_nc_ht=scontent-atl3-1.xx&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&oh=00_Af_NJVrtxTBDpSbQFwmgiOnqqJimM7TmzQ8PkZTrJmKX9w&oe=6A3699C5",
              "description": "Soft, bright glass skin with every wash .Loving this @mamaearth.in Mamaearth’s rice water face wash and Rice oil free face moisturizer combo .\n#glassskinallday #facewash #oilfree #ad #collab #aakritisharma #skincare",
              "hook": "The speaker asks if your face wash makes your skin tight and promises the secret to all-day glass skin.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 551765,
              "direct_video": "https://video-atl3-3.xx.fbcdn.net/o1/v/t2/f2/m86/AQM9wlryez2dQKwGLGgodoCPz7B-QYa_5lkxoBstJpsls-Asd5_sgAxCHR1ZVQbQgzfUUiOweTR5xgDyT9s4k69yTuywUuFKGyNBfeA.mp4?_nc_cat=111&_nc_sid=b66105&_nc_ht=video-atl3-3.xx.fbcdn.net&_nc_ohc=_xV1P7bu8vgQ7kNvwFtz4jR&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6ODg5NDQyMzM2OTQ5NzkyLCJhc3NldF9hZ2VfZGF5cyI6MTg4LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6NDYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=66517b22fdf81bbf&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8wMzQ4QUZDNkM0QTUwOUJDNzBEQkE5RDU2MjlBQTg5M192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xNDI1NTM2ODQ1NTY5Mzg3XzQ3NjI4MDgxMzAwODUxNDM5My5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmwJjW6K28lAMVAigCQzMsF0BHQAAAAAAAGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAZeadAQA&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&_nc_zt=28&oh=00_Af_FaAQUlHiEl5o4sBr2DpZfP-mJ5kG13RkOFYbZQoNWmw&oe=6A32BB64",
              "video_url": "https://www.facebook.com/ads/library/?id=1405175510898709",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Forever52 India",
              "nickname": "Forever52 India",
              "country": "india",
              "metric": "116K",
              "unit": "page likes",
              "cover": "https://scontent-lga3-3.xx.fbcdn.net/v/t39.35426-6/616603954_1865764798159070_8868335323237366178_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=i46_W-jmwAsQ7kNvwHafR6K&_nc_oc=Adp4VMuCJ51zb2Ta9qmFVseB7jTfPNrYm9tWw5K-tv8ADxw5j4pOxlJ8JGX2mKJkXyI&_nc_zt=14&_nc_ht=scontent-lga3-3.xx&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&oh=00_Af_VwpnXS-ERIwipRcXMT_LQaK6WMzMeq-XOsh0Zr3WZIQ&oe=6A36AECB",
              "description": "{{product.brand}}",
              "hook": "A close-up before-and-after shot showing a primer instantly blurring skin texture around the eye.",
              "format": "before after",
              "tier": "AD",
              "score": 115704,
              "direct_video": "https://video-lga3-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQPXSgkCQrg7Ia0ZVxG5KQKT6BCDjuTz4CgJXuimz1gTbSVKhHcQMBUhtFHVw5quPXazNkbLuWrOuEYYVaQLfwPgNzSNjez7s6HWjzXfRF9hQg.mp4?_nc_cat=103&_nc_sid=b66105&_nc_ht=video-lga3-1.xx.fbcdn.net&_nc_ohc=lFMtxaG3CLAQ7kNvwHG_des&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjEzOTI2Njk2NjIzMzcyNTcsImFzc2V0X2FnZV9kYXlzIjoxNDMsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjoyNCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=3f43c1662cbe7957&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC83QTQ2NTc4M0IxNjAyNUE4MUU3OTc3NjQ4RThBMjM5NF9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50Lzk5NDRGQTM0MTIzNzk2QjlFMEFEOUJDNzUwOUI1NDgzX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbS45rIhaj5BBUCKAJDMywXQDjEGJN0vGoYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&_nc_zt=28&oh=00_Af-tBCOqknmON1MVj0CnzLmkibFZpoKD4Jj1_X33H_Cndw&oe=6A36BB19",
              "video_url": "https://www.facebook.com/ads/library/?id=1498045572329991",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Dermorepubliq",
              "nickname": "Dermorepubliq",
              "country": "philippines",
              "metric": "63K",
              "unit": "page likes",
              "cover": "https://scontent-dfw6-1.xx.fbcdn.net/v/t39.35426-6/480990918_1306317920607112_7247938656273433383_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=j-vtB_faoC4Q7kNvwGblJ0T&_nc_oc=AdrQGi5fHzsZQnbITSUgwvbGh9DSw9P54f2cbf-0PEFvzrRr3aPvDbMZ1RW4SgpPhqE&_nc_zt=14&_nc_ht=scontent-dfw6-1.xx&_nc_gid=Kob9zNdsCgTA7i_09VBg_g&_nc_ss=72289&oh=00_Af_VkunVid0TqEcftNpSCsNc05nYFNXwG_Fi2IkF7k376Q&oe=6A368689",
              "description": "💡 Struggling with acne, dryness, or uneven skin tone? We’ve got you! Our science-based formulations are designed to deliver real, visible results at an affordable price! \n\n✨ From breakouts to brightening, Dermorepubliq has you covered! Get healthier, glowing skin with custom blends made to work for you.\n\n📍 Visit our kiosks at:\n\n📌 SM City Fairview\n📌 SM City Sta. Mesa\n📌 SM City Masinag\n📌 SM City Tanza\n📌 Riverbanks Center\n\n🛒 Prefer to shop from home? We’re available on Shopee, Lazada, and TikTok Shop!",
              "hook": "A rhythmic, split-screen visual showcasing a woman's clear skin across yellow, pink, and white backgrounds.",
              "format": "demo",
              "tier": "AD",
              "score": 63065,
              "direct_video": "https://video-dfw5-2.xx.fbcdn.net/o1/v/t2/f2/m366/AQMYuT1rmIfy9BqGVVuaKa1A99fLEHMN88GOAbxEUv2EuNr3KMJTrq1ABBd1v_qkUQ25NReunEabAin4noyb60vcPs9wwuvOnZVu3WluHrYjyA.mp4?_nc_cat=100&_nc_sid=b66105&_nc_ht=video-dfw5-2.xx.fbcdn.net&_nc_ohc=WZ88p88NNcUQ7kNvwEzLEMw&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuMTI4MC5kYXNoX2gyNjQtYmFzaWMtZ2VuMl83MjBwIiwieHB2X2Fzc2V0X2lkIjoxMzMzNTEzOTMxMzEzNTU2LCJhc3NldF9hZ2VfZGF5cyI6NDgyLCJ2aV91c2VjYXNlX2lkIjoxMDc5OSwiZHVyYXRpb25fcyI6MTUsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=64799ff2fb202162&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC8zQTQ3MDUxM0JBOTQ1RDlFOTlGMTE3NDY3NENBN0JBMF9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dKWXBqUnlRR0Y3RjFERUNBSnQ5QzF3Ul9UMUxidjRHQUFBRhUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaoxu6C3bTeBBUCKAJDMywXQC4HrhR64UgYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=Kob9zNdsCgTA7i_09VBg_g&_nc_ss=72289&_nc_zt=28&oh=00_Af_UwYV2I3KXp-uJn_Qxv5T16UMKY1tLT1-aJxCOFADjyA&oe=6A36BA2C",
              "video_url": "https://www.facebook.com/ads/library/?id=1001066478565404",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@HK Vitals",
              "nickname": "HK Vitals",
              "country": "india",
              "metric": "58K",
              "unit": "page likes",
              "cover": "https://scontent-sjc3-1.xx.fbcdn.net/v/t39.35426-6/587251801_1310731220825932_583572260386989937_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=lWA2ozlGULQQ7kNvwG7k9aD&_nc_oc=Adqdo4TlRM69389txHB_jl3jBpQf6sQx9JxruvOP5yuOSYAQQB7DQiNO4rEvfRW_Y58&_nc_zt=14&_nc_ht=scontent-sjc3-1.xx&_nc_gid=6vsJhjbmQCQ4--Z4B3X9lQ&_nc_ss=7c289&oh=00_Af9sOTi8nfzJNRuMaWi1ynOaFsYdyP490T_L5vxkd91TTg&oe=6A36AACC",
              "description": "☝️Start Your Zero Step Skincare Routine With HK Vitals Skin Radiance Collagen. 🛒Order India’s Bestselling Collagen To Reduce Fine Lines, Wrinkles & Dullness. ✨",
              "hook": "The video opens with a close-up of the HK Vitals Collagen product followed by a celebrity endorsement.",
              "format": "professional commercial",
              "tier": "AD",
              "score": 58383,
              "direct_video": "https://video-sjc6-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQO9gG-z-5N4pEtCS0JNllwYF_vg3YdoBqaVm1EE_Ebu5obgXdR8xzU-cJcZ4f0TCRA3FNENcluj8F5q8ryiFxoK5ujg4cz8HsYBCUfdEo3O_w.mp4?_nc_cat=107&_nc_sid=b66105&_nc_ht=video-sjc6-1.xx.fbcdn.net&_nc_ohc=0HTkEUT7A44Q7kNvwHeKgYU&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjM3MDE1NDE2MTAxNDA2MTAsImFzc2V0X2FnZV9kYXlzIjoyMDcsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjoyNSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=6ad73523e2354eb8&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC8yRDRFRjg5ODgwMkJFQkMxNTcyM0ZFMkY0QTI3MTg5Nl9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50Lzg0NEZBQ0FBNUFERUMyMzQ0MzE3QUQ2QzEzNDdGQjg5X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaEz9mMiqKTDRUCKAJDMywXQDkAAAAAAAAYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=6vsJhjbmQCQ4--Z4B3X9lQ&_nc_ss=7c289&_nc_zt=28&oh=00_Af8R3_gYnZcYnXD59ibSG-Us4YneiwTCNBTlON6SAs3Rww&oe=6A368ECD",
              "video_url": "https://www.facebook.com/ads/library/?id=1142250094656605",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@HK Vitals",
              "nickname": "HK Vitals",
              "country": "india",
              "metric": "58K",
              "unit": "page likes",
              "cover": "https://scontent-atl3-3.xx.fbcdn.net/v/t39.35426-6/589241770_1335763671113791_7996299616150759534_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=fNk7oRrO6loQ7kNvwHxQ0HN&_nc_oc=AdqXZOcUq90bd5cSIksa-VNNvYN116TSR9yx8u0mc1SlTsdnmj-DNmNH81OaPnHLn_s&_nc_zt=14&_nc_ht=scontent-atl3-3.xx&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&oh=00_Af9_dvvXU1dDWv2rU8wSYAy7yGVFcswMA6T6UcaohHxa5g&oe=6A36AB0F",
              "description": "☝️Start Your Zero Step Skincare Routine With HK Vitals Skin Radiance Collagen. 🛒Order India’s Bestselling Collagen To Reduce Fine Lines, Wrinkles & Dullness. ✨",
              "hook": "A woman in a red dress introduces her skincare routine starting from step three and counting backwards to step zero.",
              "format": "talking head",
              "tier": "AD",
              "score": 58383,
              "direct_video": "https://video-atl3-3.xx.fbcdn.net/o1/v/t2/f2/m366/AQNmLmiOAJbJa-WjxCewBMo1vaOgJdKFaFrILk8uloIolsHIu-47rI7ni8BNLDqfeN9Rr3C-a6XR-KKQT-zXO2h9gvVOApXFkTqYxhttpK0JDw.mp4?_nc_cat=107&_nc_sid=b66105&_nc_ht=video-atl3-3.xx.fbcdn.net&_nc_ohc=XK8I0tOyJ1MQ7kNvwHqFlN2&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjEzMDc1OTg0MDc4MzM0NDksImFzc2V0X2FnZV9kYXlzIjoyMDcsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjoyNCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=111f3edba4b48121&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC9ERjRBMjRBMzY2NEVEQUI1RjVCM0Q4RkVDRUMyMkE5MF9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50Lzk3NEJFRkYzNERDRUVEQzBCNDBGNjVFRUNENzBEMkEzX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbS3dypn9DSBBUCKAJDMywXQDgzMzMzMzMYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&_nc_zt=28&oh=00_Af_N8jfSQ2gcbH7fMvK3VRvWlm1buapN-HlWXyyf2482yA&oe=6A369C3D",
              "video_url": "https://www.facebook.com/ads/library/?id=698733229749780",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@lulu_arwa",
              "nickname": "Plix",
              "country": "india",
              "metric": "45K",
              "unit": "page likes",
              "cover": "https://scontent-atl3-3.xx.fbcdn.net/v/t39.35426-6/495512999_1673342183388342_3946424601267210136_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=1uNsaQtcz6wQ7kNvwGv_bcE&_nc_oc=Adq-QMQwh-ygzgoCzK2pnAh636LfRHUz9dH-gn0AwfGQi_SGay9ISSGKE0wqRfD3qqc&_nc_zt=14&_nc_ht=scontent-atl3-3.xx&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&oh=00_Af-sz7ZKFrf8xvHAkoPq7XTzZSWJ7mLa6g_bJq8_nF3FUA&oe=6A3692C3",
              "description": "Comment for link🖇⬇\n\nIn love with this The Guava Glow Cleanser ,toner , The Vitamin C Serum & moisturiser from @myplixlife duo‼️🤝\n\nI am using this guava range since 3 months now\n\nAfter every wash I can feel my skin getting getting better ✨\n\nPlix cleanser contains vit b 12 and vitamin c Jiska first use se hi milta h instant glow. Then plix guava glow toner is 2 in 1 toner skin ko hydrated krta h pores tighten up rkhta h and its has guava roses fat water toh maintain skin ph level. Then comes my all time favourite plix 10% vitamin c 5kda hyaluronic acid serum jiske apki skin even toner ho jygi.Last comes plix guava glow moisturiser with spf 20 vitamin c and hyaluronic acid which gives your brighter skin.",
              "hook": "The video starts with a woman showing the full range of pink Plix skincare products and a before/after skin transformation.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 44933,
              "direct_video": "https://video-atl3-2.xx.fbcdn.net/o1/v/t2/f2/m412/AQOtk6CcAfpwZb3OA8fPoz8fFtX-FzHtDJACXHIdxOzQUF-taQcl_ZJZ6iulcPgwnYJGrEmadzeqd-Q9uK-MwyaG.mp4?_nc_cat=100&_nc_sid=ef5aa3&_nc_ht=video-atl3-2.xx.fbcdn.net&_nc_ohc=mNcVJZuSAKkQ7kNvwEEyroN&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmFzaWNfaHEyX2hkX3Byb2dyZXNzaXZlIiwieHB2X2Fzc2V0X2lkIjoxNDU0NDEwNzk5NTEyMTMzLCJhc3NldF9hZ2VfZGF5cyI6NjYsInZpX3VzZWNhc2VfaWQiOjEwNjgwLCJkdXJhdGlvbl9zIjo3MiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&_nc_zt=28&oh=00_Af8VP2ZV5V9GH-eiM2zJSPW0_KXWUU_MpESNV7Wvf2Ba_A&oe=6A369421",
              "video_url": "https://www.facebook.com/ads/library/?id=1530227284793744",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Sotrue",
              "nickname": "Sotrue",
              "country": "india",
              "metric": "9K",
              "unit": "page likes",
              "cover": "https://scontent-lga3-2.xx.fbcdn.net/v/t39.35426-6/596800262_1231913595424204_382944630928026159_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=ZXGP6JkxwVAQ7kNvwFI3HHu&_nc_oc=Adqw2JiyOvpQAytmQokZmbgzyN24SfJQ6Zs31ZsYHBbjUpzWBDUxxrUgJ6WDwF2dJco&_nc_zt=14&_nc_ht=scontent-lga3-2.xx&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&oh=00_Af_cXNi0E3k6pegoxBxtWAHrkEBPBNo0NEj6AQQ3tD31fg&oe=6A36902E",
              "description": "📢 Breaking News: Viral Strobe Cream finally on Sale! ✨\n\nFor the first time ever, you can grab it in our Buy More, Glow More Sale:\n\n✔️ Any 2 for ₹499\n\nMix & match cult-favs like the Strobe Cream, Derma Roller & Sunscreen 💅\n\nBut don’t blink — this sale is ending soon and strobe lovers are hoarding already 😬\n\n💸 Prepaid pe extra off\n🚚 Free delivery\n👉https://www.sotrue.in/collections/strobe-cream",
              "hook": "Hands holding a 3-in-1 strobe cream box against a floral background.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 8816,
              "direct_video": "https://video-lga3-1.xx.fbcdn.net/o1/v/t2/f2/m366/AQNab_YgYE7cm3DjMQSSuB_f6ZcQmyvFXYKRu_66Zy2Gq-So0Mb3ulcWPnqaz9tMm7dURezlOY1cB0LvETGXPFKYZDg5qrAo4PJZDj6Egncf2g.mp4?_nc_cat=103&_nc_sid=b66105&_nc_ht=video-lga3-1.xx.fbcdn.net&_nc_ohc=CwMEEf2WLZ8Q7kNvwHkAIiK&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHAiLCJ4cHZfYXNzZXRfaWQiOjE5MjIzNzI5MzUzNzA1NDQsImFzc2V0X2FnZV9kYXlzIjoyMDgsInZpX3VzZWNhc2VfaWQiOjEwNzk5LCJkdXJhdGlvbl9zIjoyNywidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=55bc8b5f0eedcde&_nc_vs=HBksFQIYRWZiX2VwaGVtZXJhbC8xNjRGQUZBMzJEMEZBM0Y3NjlBQjY5NUMwNzNFMDVCRF9tdF8xX3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBEgAVAhhAZmJfcGVybWFuZW50LzUyNDFGNzIxRUVGNjg0MUEyNDQ1ODc4Q0I2NkE3N0ExX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbgnIK_6pjqBhUCKAJDMywXQDsUeuFHrhQYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHARAHUAZd6oAQA&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&_nc_zt=28&oh=00_Af8IFb1i6dLQDJk3D5UkRuTJT_CfEyknUDcTijP_isr3Rw&oe=6A36B691",
              "video_url": "https://www.facebook.com/ads/library/?id=1222873996644686",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Wishlink Engage Page",
              "nickname": "Plix",
              "country": "india",
              "metric": "4K",
              "unit": "page likes",
              "cover": "https://scontent-atl3-3.xx.fbcdn.net/v/t39.35426-6/601397139_1207518887478098_5163713953705703784_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=vRUsMv0IvAMQ7kNvwFLyE6j&_nc_oc=AdoTCumvo7HzkTSkZF99Xnk7xKBvgHtGqJB2ayaXSkl-Z_1jPBpp39_E0klWw2iS1q0&_nc_zt=14&_nc_ht=scontent-atl3-3.xx&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&oh=00_Af9oxxxSXt92R3fkSqqqPYUC6p--2BLhGZI49HaWxLwbqw&oe=6A36901A",
              "description": "Type \"Link\" to get Purchase links of all products direct in ur inbox or Share this reel with me to get direct links in ur inbox.\n\n@myplixlife",
              "hook": "The video starts with a woman holding a large basket full of pink skincare products, enthusiastically claiming it's a 'very good range'.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 3955,
              "direct_video": "https://video-atl3-1.xx.fbcdn.net/o1/v/t2/f2/m86/AQPCzW0XgWaFt3WMvKvJF8VyC9547mETOZEAjk0vAqRh16qLLbf2wRWC8YUoM2CmGYzZVoaK_iW_TUOdkdSomD4bGNiFlNroCC4gJ8E.mp4?_nc_cat=106&_nc_sid=b66105&_nc_ht=video-atl3-1.xx.fbcdn.net&_nc_ohc=6haENWMH_eUQ7kNvwHohPC6&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTE3MjM1ODUzNzkzNzA2MiwiYXNzZXRfYWdlX2RheXMiOjE4MSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjQ5LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=8873b55b013dccfd&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9CMTRBOEY3QUU1MEJCNzIzMjAzRDk1QTg2NEVGQzlBNl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC83MTI1NjU0NjE1ODMxOTBfNzI2ODQ1NzU5NzE3MzUwMjc3OC5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmzIKg45-QlQQVAigCQzMsF0BI2ZmZmZmaGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAZeadAQA&_nc_gid=-QRd7AXigvEw2MD8mC2Gog&_nc_ss=72289&_nc_zt=28&oh=00_Af9Nz0JMIMnJRBEejChh0_lnzyo6lqEUCNRaoS3ZDjTodQ&oe=6A32A59F",
              "video_url": "https://www.facebook.com/ads/library/?id=1510654586715185",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Harshika Varshney",
              "nickname": "Plix",
              "country": "india",
              "metric": "2K",
              "unit": "page likes",
              "cover": "https://scontent-lga3-2.xx.fbcdn.net/v/t39.35426-6/622117247_830189500039364_1969347534888837873_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=W7nSCn5FZrgQ7kNvwEvGRKo&_nc_oc=Adr-9eS6CAJS-vRhxHKqfIjcr4WVe9JIiLXCIC89TqajRYXq9gPiiuf86r-xIr0EYH0&_nc_zt=14&_nc_ht=scontent-lga3-2.xx&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&oh=00_Af_Sif24zwxLm7jvcu0jmjizAMo_DSg8vtj9WztsoIXRUA&oe=6A3684DF",
              "description": "Comment “LINK” if you want to try this glow routine ✨\nI’ve gone through multiple bottles from this range, and honestly, the Plix Guava Glow line has become a staple for me.\n\nThe cleanser feels so fresh on the skin, gel-based, juicy, and cleansing without that tight, dry feeling. \nIt gives such a nice instant glow✨\n\nThe Guava Glow Serum is what really stands out for me. It helps with dullness and brightening, and I love that the Vitamin C is formulated properly, effective yet gentle.\n\nThe moisturiser is light, hydrating, and has this smooth gel-cream texture. \n\nIt leaves the skin plump and glowy, helps with dark spots, and even has SPF 20, which is a nice bonus.\nOverall, this routine is a great pick if you’re looking for everyday glow without anything harsh. \n\nThe fruit extracts and plant-based actives make it feel super gentle on the skin❤️\n\n(Plix skincare, Plix Guava Glow, Vitamin C serum, Guava Glow Serum, gel cleanser, brightening skincare, glow routine, dewy skin, glass skin look, plant-based skincare, fruit extracts skincare, gentle skincare, dark spots, dull skin, hyperpigmentation, hydrating moisturiser, SPF moisturiser, Indian skincare routine, everyday skincare)\n\n#ad #skincare #viral #skin #routine",
              "hook": "I have finished multiple bottles of this range and I absolutely love this.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 1786,
              "direct_video": "https://video-lga3-3.xx.fbcdn.net/o1/v/t2/f2/m69/AQMSTlUXNPeTfUCdMTRmsgKIwqV7fluQti5t-g1qhn5E3LaeybX96NZEOOvAZ68MvDxJNUMsVKNw5gTF9XKMQmCS.mp4?strext=1&_nc_cat=108&_nc_sid=b66105&_nc_ht=video-lga3-3.xx.fbcdn.net&_nc_ohc=ZBBeV1qZkcMQ7kNvwGdzMGJ&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc4NzM3MTcwMTk0OTAxNDQsImFzc2V0X2FnZV9kYXlzIjoxNDUsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjozNiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=f2649423793540e&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HQ0tmNHlRUVY0cTNWd3NGQVB3QnNMOVRabWNTYnNwVEFRQUYVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0IyNDA5NUE5MTZFODhDMDAyREY2N0I4RkFEMEQ3NzlFX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbA3ZmcoYPAPxUCKAJDMywXQEIAAAAAAAAYEmRhc2hfYmFzZWxpbmVfMV92MREAdQBl5p0BAA&_nc_gid=aJPm7Fc8VpEpWaxi-EC5nw&_nc_ss=7c289&_nc_zt=28&oh=00_Af9RzL99Zhrph5b5ux7kziQZ1Zmmvr7x3_q5Te-hTtTACA&oe=6A36B1C2",
              "video_url": "https://www.facebook.com/ads/library/?id=2325992124536857",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            },
            {
              "handle": "@Prachi Arora",
              "nickname": "The Derma Co.",
              "country": "india",
              "metric": "2K",
              "unit": "page likes",
              "cover": "https://scontent-lga3-2.xx.fbcdn.net/v/t39.35426-6/654267791_1252891040320595_106720525619534162_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=Ku5xkSlI2r0Q7kNvwHD9pEj&_nc_oc=Adp1Fr2wvGhVExTiKBA_CpNpUSVodDMe45hCkvqeeWkNEc5lhuptadq3yCiUphGL6OY&_nc_zt=14&_nc_ht=scontent-lga3-2.xx&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&oh=00_Af8IiEKuPAlgQ2xUKbzfkQFL2dLCEhQgklHaQnBcAQ_GQA&oe=6A369B3C",
              "description": "From ghostly white casts to oily disasters, I finally found the one🧡\nMeet my skin’s true love - @thedermacoindia 1% Hyaluronic Aqua Gel with SPF 50 PA4+\n\nComment for link!✨\n.\n.\n.\n.\n#ad #Bestsunscreen #dermaco",
              "hook": "The speaker admits she used to skip sunscreen because it made her look like a ghost and feel oily.",
              "format": "ugc testimonial",
              "tier": "AD",
              "score": 1674,
              "direct_video": "https://video-lga3-3.xx.fbcdn.net/o1/v/t2/f2/m86/AQPnCYJA0wckKbUlnbbih5Zqi_8ODe4F3ChO5vVvAIBPPkloeaTKDVebSKGe6luCYN-JTfNV2UoSDY4R9ewTCpnxJQFxFJzPjlgnXmc.mp4?_nc_cat=108&_nc_sid=b66105&_nc_ht=video-lga3-3.xx.fbcdn.net&_nc_ohc=p4cpSmlxhwYQ7kNvwF3vNFx&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5WSV9VU0VDQVNFX1BST0RVQ1RfVFlQRS4uQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTEyOTc2NzMwOTI0ODMyMiwiYXNzZXRfYWdlX2RheXMiOjI3OCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjM5LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=22d87a8a95a91ec6&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9DMjQ3REVGNkEzNzNFNTJBRkFENjk1OTJBNDVCQkY4NF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC83ODMxNjQ4MjQyOTY4MzJfMjE1ODU2MDk4MjQ4MDk2MDE3NC5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmhJ2sso7hgQQVAigCQzMsF0BDrtkWhysCGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAZeadAQA&_nc_gid=l8UXUVnmJgYenKmqPcY-PA&_nc_ss=72289&_nc_zt=28&oh=00_Af_QQkfgR1-atWScv2o2s-FewnhuyzsOox2EunmRCWYLZQ&oe=6A32A059",
              "video_url": "https://www.facebook.com/ads/library/?id=1470370884607981",
              "platform": "paid",
              "embed_url": "",
              "picked": false
            }
          ]
        }
      ]
    }
  ]
};
